### ISSUE TITLE
"Error writing cache count for transactions - Cache Disabled" when /api/node/status is called

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-sdk#2482]
### Expected behavior
No errors in the log when /api/node/status is called

### Actual behavior
When I call the /api/node/status endpoint, I get the following error in the log:
`Error writing cache count for transactions - Cache Disabled`

### Steps to reproduce
monitor the log with `tail -f logs/lisk.log`
then call
`curl -s localhost:7000/api/node/status`

### Which version(s) does this affect? (Environment, OS, etc...)
1.1.0.rc0 on testnet

**Comment by MaciejBaj** [comment]
Worth to mention is that the API response is correct and returns a proper response. Due to the performance improvements, we decided to cache particular, hard to obtain values returned from `api/node/status` endpoint. It's up to a node maintainer to disable or enable the cache. The following message "Error writing cache count for transactions - Cache Disabled" means, that due to the cache being disable, mentioned values cannot be cached. If you want @simonmorgenthaler we could change the communication to keep it in a warning style.

**Comment by simonmorgenthaler** [comment]
Thanks @MaciejBaj , Yes, I would definitely change it to a WARNING. Or even less "important".

**Comment by ManuGowda** [comment]
@MaciejBaj as discussed with you and @fchavant I am reopening this issue as adding redundant logs `[WRN] 2018-12-17 13:54:31 | Transaction count wasn't cached - Cache Disabled` is not appropriate as we are warning the user while starting of the node that `cache` is disabled is good enough.

**Comment by ManuGowda** [comment]
```
14:25:13.867Z  WARN lisk-framework:
    Transaction count wasn't cached Error: Cache Disabled
        at Cache.setJsonForKey (/home/lisk/lisk-2.0.0-alpha.4-0829a25-Linux-x86_64/node_modules/lisk-framework/src/components/cache/cache.js:132:10)
        at Cache.wrappedFunction (/home/lisk/lisk-2.0.0-alpha.4-0829a25-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:315:51)
        at updateConfirmedCountToCache (/home/lisk/lisk-2.0.0-alpha.4-0829a25-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/transactions.js:635:9)
        at nextTask (/home/lisk/lisk-2.0.0-alpha.4-0829a25-Linux-x86_64/node_modules/async/dist/async.js:5324:14)
        at Immediate.next (/home/lisk/lisk-2.0.0-alpha.4-0829a25-Linux-x86_64/node_modules/async/dist/async.js:5331:9)
        at Immediate.<anonymous> (/home/lisk/lisk-2.0.0-alpha.4-0829a25-Linux-x86_64/node_modules/async/dist/async.js:969:16)
        at Shim.applySegment (/home/lisk/lisk-2.0.0-alpha.4-0829a25-Linux-x86_64/node_modules/newrelic/lib/shim/shim.js:1386:20)
        at Immediate.wrapper (/home/lisk/lisk-2.0.0-alpha.4-0829a25-Linux-x86_64/node_modules/newrelic/lib/shim/shim.js:2010:17)
        at runCallback (timers.js:706:11)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        at process.topLevelDomainCallback (domain.js:120:23)
```
