### ISSUE TITLE
Only accept integer range values for snapshotting rounds

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#2843]
### Expected behavior
We should accept only the integer range values for snapshotting rounds. If need to specify the full all available rounds we should use `-1` for it. 

To run full rounds snapshot we should be able to do;

```
node app.js -s -1
```

### Actual behavior
Currently we are providing different values, integer for valid rounds and non-integer for full rounds. 
https://github.com/LiskHQ/lisk/blob/cb68ebb96aacc3dccd532de6f926a1c39a2b1411/modules/loader.js#L772

e.g. Currently we can run something like this 

```
node app.js -s all
or
node app.js -s highest
or 
node app.js -s my-name
```

### Which version(s) does this affect? (Environment, OS, etc...)
all

**Comment by fchavant** [comment]
> ```
> node app.js -s -1
> ```

This is a bit confusing: it's look like we're using to switches (`-s` and `-1`)

**Comment by diego-G** [comment]
It's failing locally to me:
```[inf] 2019-04-05 14:45:40 | Snapshot mode enabled
[ERR] 2019-04-05 14:45:40 | Error: Unable to create snapshot, "--snapshot" parameter should be an integer equal to or greater than zero
    at Object.__private.createSnapshot.height [as createSnapshot] (/Users/diego-g/git/lisk/framework/src/modules/chain/submodules/loader.js:764:9)
    at library.storage.entities.Block.begin.then (/Users/diego-g/git/lisk/framework/src/modules/chain/submodules/loader.js:507:22)
    at tryCatcher (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/diego-g/git/lisk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
[inf] 2019-04-05 14:45:40 | Cleanup controller...
```
