### ISSUE TITLE
Network tests fail when running more than 2 peers

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-sdk#3296]
### Expected behavior

Network tests pass.

### Actual behavior

When the network is bigger than 2 nodes, applications are not able to start crashing with the next error:
```
2|node_2  | [inf] 2019-04-10 08:05:39 | Socket Cluster ready for incoming connections
2|node_2  | [inf] 2019-04-10 08:05:39 | Modules ready and launched
2|node_2  | [ERR] 2019-04-10 08:05:39 | Error occurred while fetching information from 127.0.0.1:5500: Event 'rpc-request' was aborted due to a bad connection
2|node_2  | [ERR] 2019-04-10 08:05:39 | Error occurred while fetching information from 127.0.0.1:5501: Event 'rpc-request' was aborted due to a bad connection
2|node_2  | { SocketProtocolError: Socket hung up
2|node_2  |     at SCClientSocket._onSCClose (/Users/diego-g/git/lisk/node_modules/socketcluster-client/lib/scclientsocket.js:654:15)
2|node_2  |     at SCTransport.<anonymous> (/Users/diego-g/git/lisk/node_modules/socketcluster-client/lib/scclientsocket.js:304:12)
2|node_2  |     at SCTransport.Emitter.emit (/Users/diego-g/git/lisk/node_modules/component-emitter/index.js:133:20)
2|node_2  |     at SCTransport._onClose (/Users/diego-g/git/lisk/node_modules/socketcluster-client/lib/sctransport.js:217:28)
2|node_2  |     at WebSocket.SCTransport.wsSocket.onerror (/Users/diego-g/git/lisk/node_modules/socketcluster-client/lib/sctransport.js:81:12)
2|node_2  |     at WebSocket.onError (/Users/diego-g/git/lisk/node_modules/socketcluster-client/node_modules/ws/lib/event-target.js:128:16)
2|node_2  |     at WebSocket.emit (events.js:189:13)
2|node_2  |     at WebSocket.EventEmitter.emit (domain.js:441:20)
2|node_2  |     at ClientRequest.req.on (/Users/diego-g/git/lisk/node_modules/socketcluster-client/node_modules/ws/lib/websocket.js:535:10)
2|node_2  |     at ClientRequest.emit (events.js:189:13)
2|node_2  |     at ClientRequest.EventEmitter.emit (domain.js:441:20)
2|node_2  |     at Socket.socketErrorListener (_http_client.js:392:9)
2|node_2  |     at Socket.emit (events.js:189:13)
2|node_2  |     at Socket.EventEmitter.emit (domain.js:441:20)
2|node_2  |     at emitErrorNT (internal/streams/destroy.js:82:8)
2|node_2  |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
2|node_2  |   name: 'SocketProtocolError',
2|node_2  |   message: 'Socket hung up',
2|node_2  |   code: 1006 }
```

The error log comes from P2P library https://github.com/LiskHQ/lisk-elements/blob/466c68ed8069f2c5b890426b1a7985585f30af35/packages/lisk-p2p/src/peer.ts#L698

### Steps to reproduce

`TOTAL_PEERS=3 npm run mocha:network`

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/create_network_module`

**Comment by shuse2** [comment]
We have found a reason of instability in the network test, and temporally disabling the network test until the next version.

Current protocol does not allow one way connection, and in the network test we are trying to connect one way.
It seems if the request is faster than disconnection, it will success but if not, it will fail
