### ISSUE TITLE
Newrelic should be optional to run lisk core

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3372]
### Expected behavior
`npm test` or any other framework test should run without any errors related to newrelic and it should not expect any newrelic env variables for running framework tests.
### Actual behavior
`npm test` or any other framework test fails with newrelic related errors.
### Steps to reproduce
`npm test`

**Comment by ManuGowda** [comment]
For the reference:
I pulled the latest development branch, then ran
```
npm ci
npm run bootstrap --ci
npm run build
node lisk/src/index.js
```
if I run without setting `NEW_RELIC_LICENSE_KEY` it works.
When I run `NEW_RELIC_LICENSE_KEY=a3828d6af3f59b6ff2ab818036df5036324f37f0 node lisk/src/index.js`
I am getting the following error
```
lisk-sdk git/development
❯ node lisk/src/index.js
Unable to find New Relic module configuration. A default
configuration file can be copied from /Users/manu/lisk_ecosystem/lisk-sdk/framework/node_modules/newrelic/lib/config/default.js
and put at /Users/manu/lisk_ecosystem/lisk-sdk/newrelic.js or
/Users/manu/lisk_ecosystem/lisk-sdk/lisk/src/newrelic.js. If you are not using file based config
please set the environment variable NEW_RELIC_NO_CONFIG_FILE=true
Unable to find New Relic module configuration. A default
configuration file can be copied from /Users/manu/lisk_ecosystem/lisk-sdk/framework/node_modules/newrelic/lib/config/default.js
and put at /Users/manu/lisk_ecosystem/lisk-sdk/newrelic.js or
/Users/manu/lisk_ecosystem/lisk-sdk/lisk/src/newrelic.js. If you are not using file based config
please set the environment variable NEW_RELIC_NO_CONFIG_FILE=true
/Users/manu/lisk_ecosystem/lisk-sdk/framework/node_modules/lisk-newrelic/src/index.js:118
			this.newrelic.shim.isArray(callbackFunctions) ||
			                   ^

TypeError: Cannot read property 'isArray' of undefined
    at LiskNewRelic.instrumentCallbackMethods (/Users/manu/lisk_ecosystem/lisk-sdk/framework/node_modules/lisk-newrelic/src/index.js:118:23)
    at Object.keys.forEach.modulePath (/Users/manu/lisk_ecosystem/lisk-sdk/framework/src/modules/chain/helpers/newrelic_lisk.js:90:15)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/manu/lisk_ecosystem/lisk-sdk/framework/src/modules/chain/helpers/newrelic_lisk.js:89:34)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

- The expectation is newrelic should be optional to run `lisk-core`
- If there an issue with the newrelic license key or any other general issue with newrelic, the error should be handled gracefully

**Comment by nazarhussain** [comment]
The error is not because newrelic module, its because its config file seems missing.

**Comment by ManuGowda** [comment]
For the reference:
I pulled the latest development branch, then ran
```
npm ci
npm run bootstrap --ci
npm run build
node lisk/src/index.js
```
if I run without setting `NEW_RELIC_LICENSE_KEY` it works.
When I run `NEW_RELIC_LICENSE_KEY=dummkey node lisk/src/index.js`
I am getting the following error
```
lisk-sdk git/development
❯ node lisk/src/index.js
Unable to find New Relic module configuration. A default
configuration file can be copied from /Users/manu/lisk_ecosystem/lisk-sdk/framework/node_modules/newrelic/lib/config/default.js
and put at /Users/manu/lisk_ecosystem/lisk-sdk/newrelic.js or
/Users/manu/lisk_ecosystem/lisk-sdk/lisk/src/newrelic.js. If you are not using file based config
please set the environment variable NEW_RELIC_NO_CONFIG_FILE=true
Unable to find New Relic module configuration. A default
configuration file can be copied from /Users/manu/lisk_ecosystem/lisk-sdk/framework/node_modules/newrelic/lib/config/default.js
and put at /Users/manu/lisk_ecosystem/lisk-sdk/newrelic.js or
/Users/manu/lisk_ecosystem/lisk-sdk/lisk/src/newrelic.js. If you are not using file based config
please set the environment variable NEW_RELIC_NO_CONFIG_FILE=true
/Users/manu/lisk_ecosystem/lisk-sdk/framework/node_modules/lisk-newrelic/src/index.js:118
			this.newrelic.shim.isArray(callbackFunctions) ||
			                   ^

TypeError: Cannot read property 'isArray' of undefined
    at LiskNewRelic.instrumentCallbackMethods (/Users/manu/lisk_ecosystem/lisk-sdk/framework/node_modules/lisk-newrelic/src/index.js:118:23)
    at Object.keys.forEach.modulePath (/Users/manu/lisk_ecosystem/lisk-sdk/framework/src/modules/chain/helpers/newrelic_lisk.js:90:15)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/manu/lisk_ecosystem/lisk-sdk/framework/src/modules/chain/helpers/newrelic_lisk.js:89:34)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

- The expectation is newrelic should be optional to run `lisk-core`
- If there an issue with the newrelic license key or any other general issue with newrelic, the error should be handled gracefully

**Comment by nazarhussain** [comment]
@ManuGowda I just tested the issue. Its something related to the `cwd` you used to run the app. 

Logically you should be in the directory where `package.json` file for Lisk exits. If you run below it will works good and show you analytics. 

```
cd lisk
NEW_RELIC_LICENSE_KEY=xxxxxx node src/index.js
```

Although I found another issue with NewRelic https://github.com/LiskHQ/lisk-sdk/issues/3435 and fixed it. 

Please test and see if it works for you.

**Comment by ManuGowda** [comment]
Closing this issue after verification, 
Test:
`LISK_CONSOLE_LOG_LEVEL=debug NEW_RELIC_LICENSE_KEY= node src/index.js --network=mainnet`
`LISK_CONSOLE_LOG_LEVEL=debug NEW_RELIC_LICENSE_KEY=xxxxxxx node src/index.js --network=mainnet`
in the current directory of lisk, it should work.
