### ISSUE TITLE
Docker container with v1.6.0 doesn't startup due to db connection

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [LiskHQ/lisk-sdk#3472]
### Expected behavior
Lisk 1.6.0 starts and syncs to blockchain
### Actual behavior
```
# grep VERSION .env
ENV_LISK_VERSION=1.6.0
# docker-compose up
Starting docker_db_1 ... done
Recreating docker_lisk_1 ... done
Attaching to docker_db_1, docker_lisk_1
db_1    | 2019-04-29 14:14:57.733 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1    | 2019-04-29 14:14:57.733 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1    | 2019-04-29 14:14:57.855 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
lisk_1  | wait-for-it.sh: waiting 15 seconds for db:5432
db_1    | 2019-04-29 14:14:57.868 UTC [18] LOG:  database system was shut down at 2019-04-29 14:13:36 UTC
db_1    | 2019-04-29 14:14:57.872 UTC [1] LOG:  database system is ready to accept connections
lisk_1  | wait-for-it.sh: db:5432 is available after 0 seconds
db_1    | 2019-04-29 14:14:59.062 UTC [25] LOG:  incomplete startup packet
lisk_1  | internal/modules/cjs/loader.js:583
lisk_1  |     throw err;
lisk_1  |     ^
lisk_1  | 
lisk_1  | Error: Cannot find module '/home/lisk/lisk/app.js'
lisk_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
lisk_1  |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
lisk_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
lisk_1  |     at startup (internal/bootstrap/node.js:283:19)
lisk_1  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
db_1    | 2019-04-29 14:15:00.590 UTC [26] LOG:  incomplete startup packet
lisk_1  | internal/modules/cjs/loader.js:583
lisk_1  |     throw err;
lisk_1  |     ^
lisk_1  | 
lisk_1  | Error: Cannot find module '/home/lisk/lisk/app.js'
lisk_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
lisk_1  |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
lisk_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
lisk_1  |     at startup (internal/bootstrap/node.js:283:19)
lisk_1  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
docker_lisk_1 exited with code 1
db_1    | 2019-04-29 14:15:02.234 UTC [27] LOG:  incomplete startup packet
lisk_1  | internal/modules/cjs/loader.js:583
lisk_1  |     throw err;
lisk_1  |     ^
lisk_1  | 
lisk_1  | Error: Cannot find module '/home/lisk/lisk/app.js'
lisk_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
lisk_1  |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
lisk_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
lisk_1  |     at startup (internal/bootstrap/node.js:283:19)
lisk_1  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
docker_lisk_1 exited with code 1
db_1    | 2019-04-29 14:15:03.882 UTC [28] LOG:  incomplete startup packet
lisk_1  | internal/modules/cjs/loader.js:583
lisk_1  |     throw err;
lisk_1  |     ^
lisk_1  | 
lisk_1  | Error: Cannot find module '/home/lisk/lisk/app.js'
lisk_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
lisk_1  |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
lisk_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
lisk_1  |     at startup (internal/bootstrap/node.js:283:19)
lisk_1  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
### Steps to reproduce
edit `.env` to use version 1.6.0 instad of 1.5.0
### Which version(s) does this affect? (Environment, OS, etc...)
```
# cat /etc/*release* && rpm -qa | grep docker
CentOS Linux release 7.6.1810 (Core) 
Derived from Red Hat Enterprise Linux 7.6 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core) 
CentOS Linux release 7.6.1810 (Core) 
cpe:/o:centos:centos:7
docker-ce-18.09.5-3.el7.x86_64
docker-ce-cli-18.09.5-3.el7.x86_64
```

**Comment by ManuGowda** [comment]
Hi @KrzysztofHajdamowicz, your `docker-compose.yml` is outdated as we no longer have `app.js`.
In order to get it working, You can either download the latest `docker-compose.yml` from [here](https://raw.githubusercontent.com/LiskHQ/lisk-sdk/development/lisk/docker/docker-compose.yml) or you can edit your existing compose file and update path from `/home/lisk/lisk/app.js` to `/home/lisk/lisk/src/index.js`.
