### ISSUE TITLE
API returns incorrect error for postTransactions

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-sdk#3586]
### Expected behavior
API should return the correct error message.
### Actual behavior
API always returns `Invalid transaction body` error even when the transaction failed from a different reason.
```
10:01:51.954Z  WARN lisk-framework: Balance queue 775
10:01:51.954Z DEBUG lisk-framework: Received transaction 1944531498676575052 from public client
10:01:51.960Z DEBUG lisk-framework: Transaction 1944531498676575052 Error: Transaction pool is full
```
```
{ APIError: Invalid transaction body
       at axios_1.default.request.then.catch (lisk-core/qa/node_modules/@liskhq/lisk-api-client/dist-node/api_resource.js:43:27)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     jse_shortmsg: 'Invalid transaction body',
     jse_info: {},
     message: 'Invalid transaction body',
     name: 'APIError',
     errno: 409,
     errors: {} }
```
### Steps to reproduce
Send transaction when the transaction pool is full.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.0`

**Comment by 4miners** [comment]
The issue is still not fixed in `2.0.0-alpha.0`, for example for type 5 transactions I'm still getting `Invalid transaction body`, while the real error is:
```
08:33:11.520Z DEBUG lisk-framework:
    Transaction normalization failed { id: '3553007483528537995',
      err:
       'Transaction: 3553007483528537995 failed at : Transaction type 5 is currently not allowed.',
      module: 'transport' }
```

Also, for signatures, I'm getting `Error processing signature`, while the real error is:
```
08:33:11.571Z ERROR lisk-framework:
    Unable to process signature, corresponding transaction not found { signature:
       { transactionId: '3553007483528537995',
         publicKey:
          '74a7b7ecd0388fb6666cdebb682845daab855df50eb2e94be8437beb5af9bc7b',
         signature:
          'cd5ef24c048919b94a7aa2687cdb3c1b885ec3d9c4e1f7131459b5a14fc450a257875a3b97d36f47371a621600838c867c5df8b1dc3c6cc30d7ae9ba05462501' } }
```
Please also notice the inconsistency in log levels here - `DEBUG` vs `ERROR`.
