### ISSUE TITLE
Rebuild/Verification failed for testnet and mainnet

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3668]
### Expected behavior
Rebuild/Verification should succeed for both testnet and mainnet 
### Actual behavior
I have configured the node with `config`
```
{
  "modules": {
    "http_api": {
      "access": {
        "whiteList": ["127.0.0.1","62.23.239.233"]
      }
    },
    "chain": {
      "exceptions": {
        "precedent": {
          "disableDappTransaction": 8274138
        }
      }
    }
  }
}
```
# Testnet failure
```
05:39:05.384Z  INFO lisk-framework: Verify->verifyBlock succeeded for block 10082881764064460425 at height 34401.
05:39:05.387Z ERROR lisk-framework:
    Rebuilding failed [ { TransactionError: Transaction type 5 is currently not allowed.
          at transactionsResponses.transactions.map.transaction (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/process_transactions.js:178:9)
          at Array.map (<anonymous>)
          at ProcessTransactions.checkAllowedTransactions (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/process_transactions.js:165:40)
          at Object.__private.checkTransactions (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/blocks/verify.js:121:4)
          at checkTransactions (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/blocks/verify.js:805:7)
          at /home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:3880:24
          at replenish (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:1011:17)
          at iterateeCallback (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:995:17)
          at /home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:969:16
          at Immediate.<anonymous> (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:3885:13)
          at runCallback (timers.js:705:18)
          at tryOnImmediate (timers.js:676:5)
          at processImmediate (timers.js:658:5)
          at process.topLevelDomainCallback (domain.js:120:23)
        message: 'Transaction type 5 is currently not allowed.',
        name: 'TransactionError',
        id: '366869793417060333',
        dataPath: '',
        actual: undefined,
        expected: undefined } ]
```

# Mainnet failure
```
07:19:25.494Z  INFO lisk-framework: Verify->verifyBlock succeeded for block 6450512063801457100 at height 627307.
07:19:25.495Z ERROR lisk-framework:
    Rebuilding failed [ { TransactionError: Transaction type 5 is currently not allowed.
          at transactionsResponses.transactions.map.transaction (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/process_transactions.js:178:9)
          at Array.map (<anonymous>)
          at ProcessTransactions.checkAllowedTransactions (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/process_transactions.js:165:40)
          at Object.__private.checkTransactions (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/blocks/verify.js:121:4)
          at checkTransactions (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/blocks/verify.js:805:7)
          at /home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:3880:24
          at replenish (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:1011:17)
          at iterateeCallback (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:995:17)
          at /home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:969:16
          at Immediate.<anonymous> (/home/lisk/lisk-2.0.0-alpha.7-ff617db-Linux-x86_64/node_modules/async/dist/async.js:3885:13)
          at runCallback (timers.js:705:18)
          at tryOnImmediate (timers.js:676:5)
          at processImmediate (timers.js:658:5)
          at process.topLevelDomainCallback (domain.js:120:23)
        message: 'Transaction type 5 is currently not allowed.',
        name: 'TransactionError',
        id: '15359945250124697273',
        dataPath: '',
        actual: undefined,
        expected: undefined } ]
```
### Steps to reproduce
Run rebuild/verification against testnet and mainnet `node dist/index.js -n testnet -b 20000`
### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by limiaspasdaniel** [comment]
Will take a look at this too

**Comment by ManuGowda** [comment]
> Will take a look at this too

I think @lsilvs is also working on this, so please talk to each other and make sure both are not working on the same 👍

**Comment by lsilvs** [comment]
@ManuGowda I couldn't replicate the issue.

```
{"name":"lisk-framework","msg":"Verify->verifyBlock succeeded for block 10082881764064460425 at height 34401.","src":{"file":"/blocks/verify.js","line":527,"func":"Verify.verifyBlock"},"v":0}
...
{"name":"lisk-framework","msg":"Rebuilding finished","src":{"file":"/loader.js","line":783,"func":"__private.rebuildFinished.err"},"v":0}
```

I've tested using Lisk Core `v2.0.0-alpha.8` and Lisk SDK `release/2.0.0`

Can you give more information about the setup you are using, pls?

**Comment by ManuGowda** [comment]
This issue occurred as the custom config with dapp disable was not passed as an argument while verifying, so closing this issue.
