### ISSUE TITLE
Node upgrade failed due to schema validation errors

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3844]
### Expected behavior
- Node upgrade should be able to upgrade from old version to new version of Lisk core
- ## Please add some test to cover these scenarios(its a recurring issue in every release) ##
- Please do not throw error stack, instead provide a readable error message to the end user
### Actual behavior
```
/home/lisk/lisk-test/node_modules/lisk-framework/src/controller/validator/index.js:106
			throw new SchemaValidationError(parserAndValidator.errors);
			^

Error: Schema validation error
    at new SchemaValidationError (/home/lisk/lisk-test/node_modules/lisk-framework/src/errors.js:39:3)
    at parseEnvArgAndValidate (/home/lisk/lisk-test/node_modules/lisk-framework/src/controller/validator/index.js:106:10)
    at Configurator.getConfig (/home/lisk/lisk-test/node_modules/lisk-framework/src/controller/configurator/configurator.js:76:10)
    at Object.<anonymous> (/home/lisk/lisk-test/dist/helpers/config.js:64:40)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/lisk/lisk-test/scripts/generate_config.js:22:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
Lisk configured for testnet
Stopping Lisk to reload PM2 config
[+] Lisk stopped successfully.
[+] Lisk started successfully.
[+] Lisk is running as PID: 396
psql.bin: FATAL:  database "lisk" does not exist
Current Block Height:  Unavailable
```
### Steps to reproduce
- Deploy Lisk Core 1.6.0-rc.4 node
- Make sure to have the custom config with following details
```
{
  "api": {
    "access": {
      "whiteList": ["127.0.0.1","62.23.239.233"]
    }
  },
  "peers": {
    "list": [{"ip": "94.237.46.149", "wsPort": "7001"}]
  }
}
```
- Upgrade to latest build `./installLisk.sh upgrade -r test -d /home/lisk/ -0 no -f lisk-2.0.0-alpha.12-f8059085b-0d6305c-Linux-x86_64.tar.gz`
### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

**Comment by ManuGowda** [comment]
Issue moved to [LiskHQ/lisk-core #77](https://github.com/LiskHQ/lisk-core/issues/77) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ManuGowda** [comment]
Issue moved to [LiskHQ/lisk-core #78](https://github.com/LiskHQ/lisk-core/issues/78) via [**ZenHub**](https://www.zenhub.com/)
