### ISSUE TITLE
Duplicate key value violates unique constraint address_unique

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#3897]
### Expected behavior
Should not insert a record which already exists
### Actual behavior
```
10:05:00.273Z ERROR lisk-framework:
    Caused error during cleanup { error: duplicate key value violates unique constraint "address_unique"
        at Connection.parseE (/home/lisk/lisk-2.0.0-rc.0-f5bc2760c-e629652-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
        at Connection.parseMessage (/home/lisk/lisk-2.0.0-rc.0-f5bc2760c-e629652-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
        at Socket.<anonymous> (/home/lisk/lisk-2.0.0-rc.0-f5bc2760c-e629652-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
        at Socket.emit (events.js:189:13)
        at Socket.EventEmitter.emit (domain.js:441:20)
        at addChunk (_stream_readable.js:284:12)
        at readableAddChunk (_stream_readable.js:265:11)
        at Socket.Readable.push (_stream_readable.js:220:10)
        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
      name: 'error',
      length: 218,
      severity: 'ERROR',
      code: '23505',
      detail: 'Key (ip, "wsPort")=(134.209.250.246, 5000) already exists.',
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: 'public',
      table: 'peers',
      column: undefined,
      dataType: undefined,
      constraint: 'address_unique',
      file: 'nbtinsert.c',
      line: '434',
      routine: '_bt_check_unique' }
```
### Steps to reproduce
- Deploy a network from release branch 2.2.0(sdk) and core(development) branch
- Enable forging
### Which version(s) does this affect? (Environment, OS, etc...)
2.2.0

**Comment by ishantiw** [comment]
I tried to re-create the above issue and is only possible when deletion of peers from the database was not called or finished properly. In that case it will throw the above error. To test it, I removed this line and I'm able to see the above error. 

https://github.com/LiskHQ/lisk-sdk/blob/f5bc2760c7dca99282be3c3fb29e6458f7c976be/framework/src/modules/network/network.js#L311

**Comment by ManuGowda** [comment]
after merging `2.0.0` changes and `2.1.0` changes to `2.2.0` this issue doesn't exist anymore, so closing this issue.
