### ISSUE TITLE
Sequence should not be used in Loader

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#3977]
### Expected behavior

sequence is a property of loader

### Actual behavior

sequence is not a property of loader causing an error on startup

```[2019-07-17T15:03:36.259Z] ERROR: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:99 in async.retry.err):
    Unconfirmed transactions loader Error: [object Object]
        at /Users/pablo/Documents/LISK/Repos/lisk-sdk/node_modules/async/dist/async.js:205:62
        at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-07-17T15:03:36.259Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.260Z] DEBUG: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/rounds/delegates.js:230 in updateDelegateListCache): Updating delegate list cache for round 1
[2019-07-17T15:03:36.262Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.264Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.264Z] DEBUG: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/rounds/rounds.js:208 in Tick): Performing forward tick
[2019-07-17T15:03:36.268Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.269Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.270Z] ERROR: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:111 in async.retry.err):
    Signatures loader TypeError: Cannot read property 'add' of undefined
        at Loader._getSignaturesFromNetwork (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:192:23)
        at process._tickCallback (internal/process/next_tick.js:68:7)```

### Steps to reproduce

### Which version(s) does this affect? (Environment, OS, etc...)

2.2.*

**Comment by shuse2** [comment]
Signature sequence is not needed anymore
