### ISSUE TITLE
Framework should handle the cleanup successfully when failed on initialization

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4093]
### Expected behavior
Following up of 
https://github.com/LiskHQ/lisk-sdk/issues/4036

Framework should stop and cleanup properly when it fails to initialize the application.

### Actual behavior
From the log provided, it seems it's not cleaning up properly and continues the application

```
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"New peer found event: Discovered peer 46.101.218.57:7001","time":"2019-08-03T03:28:04.616Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":60,"msg":"System error: unhandledRejection : { message: 'ENOENT: no such file or directory, open \\'./ssl/lisk.key\\'',\n  stack:\n   'Error: ENOENT: no such file or directory, open \\'./ssl/lisk.key\\'\\n    at Object.openSync (fs.js:438:3)\\n    at Object.readFileSync (fs.js:343:35)\\n    at module.exports (/home/ubuntu/lisk-test/node_modules/lisk-framework/src/modules/http_api/init_steps/setup_servers.js:52:19)\\n    at HttpApi.bootstrap (/home/monamona/lisk-test/node_modules/lisk-framework/src/modules/http_api/http_api.js:109:13)' }","time":"2019-08-03T03:28:04.648Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Cleaning chain...","time":"2019-08-03T03:28:04.649Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Cleaning network...","time":"2019-08-03T03:28:04.652Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Cleanup controller...","time":"2019-08-03T03:28:04.649Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":50,"msg":"Reason: ENOENT: no such file or directory, open './ssl/lisk.key'","time":"2019-08-03T03:28:04.649Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Cleaned up successfully","time":"2019-08-03T03:28:04.651Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Saved all the peers to DB that have been tried","time":"2019-08-03T03:28:04.660Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Blocks 8914319","time":"2019-08-03T03:28:04.990Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Genesis block matched with database","time":"2019-08-03T03:28:04.991Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Validating current block with height 8914319","time":"2019-08-03T03:28:05.024Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Loader->validateBlock Validating block 2624920164477505116 at height 8914319","time":"2019-08-03T03:28:05.024Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Verify->verifyBlock succeeded for block 2624920164477505116 at height 8914319.","time":"2019-08-03T03:28:05.032Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Loader->validateBlock Validating block succeed for 2624920164477505116 at height 8914319.","time":"2019-08-03T03:28:05.032Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Finished validating the chain. You are at height 8914319.","time":"2019-08-03T03:28:05.033Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Blockchain ready","time":"2019-08-03T03:28:05.033Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Peer connect event: Connected to peer 188.166.100.144:7001","time":"2019-08-03T03:28:05.685Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"New peer found event: Discovered peer 188.166.100.144:7001","time":"2019-08-03T03:28:05.943Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Starting sync","time":"2019-08-03T03:28:14.621Z","v":0}
{"name":"lisk-framework","hostname":"lisk99.mzpool.net","pid":31170,"level":30,"msg":"Finished sync","time":"2019-08-03T03:28:15.183Z","v":0}
```

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.1-

**Comment by ManuGowda** [comment]
Tested the behavior by adding SSL configuration and followed the step as defined in #4036, with 3.0.0 the clean up is handled.
```
14:13:34.016Z  INFO lisk-framework: Enabled Lisk APM (module=http_api, service-name=Lisk-APM, uriPath=/http-stats)
14:13:34.042Z FATAL lisk-framework: System error: unhandledRejection (module=lisk-controller, err.code=ENOENT)
    Error: ENOENT: no such file or directory, open '/Users/manu/lisk_ecosystem/lisk-core/qa/localhost.keya'
        at Object.openSync (fs.js:443:3)
        at Object.readFileSync (fs.js:343:35)
        at module.exports (/Users/manu/lisk_ecosystem/lisk-sdk/framework/src/modules/http_api/init_steps/setup_servers.js:64:19)
        at HttpApi.bootstrap (/Users/manu/lisk_ecosystem/lisk-sdk/framework/src/modules/http_api/http_api.js:152:13)
        at process._tickCallback (internal/process/next_tick.js:68:7)
14:13:34.042Z  INFO lisk-framework: Cleanup controller... (module=lisk-controller)
14:13:34.042Z ERROR lisk-framework: Reason: ENOENT: no such file or directory, open '/Users/manu/lisk_ecosystem/lisk-core/qa/localhost.keya' (module=lisk-controller)
14:13:34.046Z  INFO lisk-framework: Cleaning chain... (module=chain)
14:13:34.046Z  INFO lisk-framework: PgpAdapter: Disconnect event triggered (module=chain:database)
14:13:34.047Z  INFO lisk-framework: Cleaned up successfully (module=chain)
14:13:34.047Z  INFO lisk-framework: Cleaning network... (module=network)
14:13:34.049Z  INFO lisk-framework: Cleaning HTTP API... (module=http_api)
14:13:34.049Z DEBUG lisk-framework: Cache: Clean up database (module=http_api)
14:13:34.049Z DEBUG lisk-framework: Cache: Quit database (module=http_api)
14:13:34.049Z  INFO lisk-framework: PgpAdapter: Disconnect event triggered (module=http_api:database)
14:13:34.050Z  INFO lisk-framework: Cleaned up successfully (module=http_api)
14:13:34.050Z  INFO lisk-framework: Unload completed (module=lisk-controller)
14:13:34.050Z  INFO lisk-framework: Shutting down application (module=lisk-controller, errorCode=1)
    message: ENOENT: no such file or directory, open '/Users/manu/lisk_ecosystem/lisk-core/qa/localhost.keya'
14:13:34.050Z  INFO lisk-framework: Cleanup controller... (module=lisk-controller)
14:13:34.050Z ERROR lisk-framework: Reason: 1 (module=lisk-controller)
```
