### ISSUE TITLE
BFT: Error occurred during synchronization

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4532]
### Expected behavior
- Rename table `temp block` to `temp blocks`
- During synchronization the temp blocks deletion should be handled properly
### Actual behavior
```
09:14:10.237Z DEBUG lisk-framework: Received tip of the chain from peer (module=chain, peerId=134.209.166.150:5000, blockId=923313856981135964)
09:14:10.238Z DEBUG lisk-framework: Validating detached block (module=chain, id=923313856981135964, height=16038)
09:14:10.239Z DEBUG lisk-framework: Reverting chain to the last common block with peer (module=chain, peerId=134.209.166.150:5000)
09:14:10.239Z DEBUG lisk-framework: Requesting the last common block from peer (module=chain, peerId=134.209.166.150:5000)
09:14:10.320Z DEBUG lisk-framework: Found common block (module=chain, blockId=12727341266616364462)
09:14:10.321Z DEBUG lisk-framework: Deleting blocks after common block (module=chain, blockId=12727341266616364462, height=5454)
09:14:10.322Z DEBUG lisk-framework: Deleting last block (module=chain, id=14858750031150783735, height=5455)
09:14:10.351Z ERROR lisk-framework: Error occurred during synchronization. (module=chain, err.code=23505)
    error: duplicate key value violates unique constraint "temp_block_pkey"
        at Connection.parseE (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
        at Connection.parseMessage (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
        at Socket.<anonymous> (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
        at Socket.emit (events.js:210:5)
        at Socket.EventEmitter.emit (domain.js:476:20)
        at addChunk (_stream_readable.js:308:12)
        at readableAddChunk (_stream_readable.js:289:11)
        at Socket.Readable.push (_stream_readable.js:223:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```
### Steps to reproduce
Synchrinize to network from scratch http://byzantine-seed-01.liskdev.net:6040/
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0-alpha.2

**Comment by ManuGowda** [comment]
Due to this deadlock, the node is not able to complete the sync operation. 
Additional logs
```
09:14:00.596Z DEBUG lisk-framework: Deleting last block (module=chain, id=14858750031150783735, height=5455)
09:14:00.623Z ERROR lisk-framework: Error occurred during synchronization. (module=chain, err.code=23505)
    error: duplicate key value violates unique constraint "temp_block_pkey"
        at Connection.parseE (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
        at Connection.parseMessage (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
        at Socket.<anonymous> (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
        at Socket.emit (events.js:210:5)
        at Socket.EventEmitter.emit (domain.js:476:20)
        at addChunk (_stream_readable.js:308:12)
        at readableAddChunk (_stream_readable.js:289:11)
        at Socket.Readable.push (_stream_readable.js:223:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
09:14:00.640Z DEBUG lisk-framework: Starting to process block (module=chain, id=17717011780055190126, height=16037)
09:14:00.642Z DEBUG lisk-framework: Detected different chain to sync (module=chain, id=17717011780055190126, height=16037)
09:14:00.643Z  INFO lisk-framework: Starting synchronizer (module=chain, blockId=17717011780055190126, height=16037)
09:14:00.644Z DEBUG lisk-framework: Validating detached block (module=chain, id=17717011780055190126, height=16037)
09:14:00.645Z DEBUG lisk-framework: Client is syncing. Can't process new block at the moment. (module=chain, blockId=17717011780055190126, height=16037)
09:14:00.645Z DEBUG lisk-framework: Starting to process block (module=chain, id=17717011780055190126, height=16037)
09:14:00.646Z DEBUG lisk-framework: Detected different chain to sync (module=chain, id=17717011780055190126, height=16037)
09:14:00.651Z ERROR lisk-framework: Error occurred during synchronization. (module=chain)
    Error: Synchronizer is already running
        at Synchronizer.run (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/synchronizer/synchronizer.js:94:10)
        at Immediate.<anonymous> (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/chain.js:624:23)
        at processImmediate (internal/timers.js:441:21)
        at process.topLevelDomainCallback (domain.js:131:23)
```
