### ISSUE TITLE
P2P selectPeersForConnection unit test fails randomly

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-sdk#4599]
### Expected behavior
Test should pass consistently.
### Actual behavior
Test fails randomly with following errors:

```
 1) peer selector
       #selectPeersForConnection
         when there are less than 100 peers
           should return peers uniformly from both lists:
      AssertionError: expected 18 to be at least 23
      + expected - actual
      -18
      +23
      at Context.<anonymous> (test/unit/utils/select.ts:379:27)
      at processImmediate (internal/timers.js:439:21)
```
### Steps to reproduce
```
cd elements/lisk-p2p
npm test
```
### Which version(s) does this affect? (Environment, OS, etc...)
v3.0

**Comment by valamidev** [comment]
Solved in #4616
