### ISSUE TITLE
TypeError: Converting circular structure to JSON with Node 12.14.1

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#4667]
### Expected behavior

The application should work well after upgrading to `Node 12.14.1`. 

### Actual behavior

While upgrading and trying with `Node 12.14.1` caused this Type error. It works well with `12.14.0`

```
(base) ➜  lisk-sdk-review git:(release/3.0.0) ✗ node framework/test/test_app/index.js | npx bunyan -o short
15:15:36.116Z  INFO lisk-framework: Booting the application with Lisk Framework(0.1.0) (module=lisk-controller)
15:15:36.118Z  INFO lisk-framework: Starting the app - lisk-devnet-4000 (module=lisk-controller)
15:15:36.131Z  INFO lisk-framework: Initializing controller (module=lisk-controller)
15:15:36.140Z  INFO lisk-framework: Loading controller (module=lisk-controller)
15:15:36.261Z  INFO lisk-framework: Previous Lisk PID (module=lisk-controller)
15:15:36.262Z  INFO lisk-framework: Current Lisk PID (module=lisk-controller)
15:15:36.301Z  INFO lisk-framework-chain: Loading in-memory module (module=lisk-controller, version=0.1.0, moduleAlias=chain)
15:15:36.318Z ERROR lisk-framework: (module=chain)
    Converting circular structure to JSON
        --> starting at object with constructor 'Socket'
        |     property '_writableState' -> object with constructor 'WritableState'
        |     property 'afterWriteTickInfo' -> object with constructor 'Object'
        --- property 'stream' closes the circle
    --
    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Socket'
        |     property '_writableState' -> object with constructor 'WritableState'
        |     property 'afterWriteTickInfo' -> object with constructor 'Object'
        --- property 'stream' closes the circle
        at JSON.stringify (<anonymous>)
        at Object.toJson (/Users/nazar/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/utils/index.js:221:21)
        at Function.createContextKey (/Users/nazar/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/database-pool.js:90:26)
        at Function.register (/Users/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/database-pool.js:33:36)
        at new Database (/Users/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/database.js:447:18)
        at inst (/Users/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/main.js:242:20)
``` 

### Steps to reproduce

Apparently it seems the issue with `Pg-Promise` but I tried it in a new script file 

```js
const pgpLib = require('pg-promise');

const pgpOptions = {
	capSQL: true,
	promiseLib: Promise,
	noLocking: false,
};

const pgp = pgpLib(pgpOptions);

const {
	components: { storage: dbConfig },
} = require('./test/fixtures/config/devnet/config');

const db = pgp(dbConfig);

db.connect()
	.then(() => {
		console.log('connected');
	})
	.catch(error => console.error('error', error));

```

The above script works well with both node versions. Also tests with latest Pg-Promise `10.13.2` as well and same issue. 

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0, Node 12.14.1

**Comment by nazarhussain** [comment]
For details on why this issue is triggered, look at the https://github.com/nodejs/node/issues/31277

We still have a workaround in our product, so will proceed with it.

**Comment by leeftk** [comment]
Hey all I am still receiving this issue on my device, is there any fix for it?
