### ISSUE TITLE
One usage of BigNum is still present

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#4725]
### Expected behavior

There're are not usages of BigNum functions that interrupt the blockchain

### Actual behavior

`framework/src/modules/chain/block_processor_v2.js` is using`block.reward = block.reward.times(0.25);` this should be changed to BigInt

### Steps to reproduce

Run a devnet blockchain with some blocks in it and you'll get error 

```
TypeError: block.reward.times is not a function
        at BlockProcessorV2._create (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/block_processor_v2.js:363:32)
        at /Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/block_processor_v2.js:285:24
        at async Pipeline.run (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/processor/pipeline.js:55:18)
        at async Forger.forge (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/forger/forger.js:306:23)
        at async Object.worker (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/chain.js:530:5)
        at async Sequence._tick (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/utils/sequence.js:54:19)
        at async Timeout.nextSequence [as _onTimeout] (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/utils/sequence.js:41:4)
```

### Which version(s) does this affect? (Environment, OS, etc...)

4.0.0

**Comment by pablitovicente** [comment]
Given the code is using a float this needs to be changed to a multiplication by a fraction.
