### ISSUE TITLE
Downloading transactions should wait for network have at least one connection

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#4785]
### Description

Requesting any RPC action should wait until the network has at least one connection.

### Motivation

It always fail to get the transactions/signatures on startup.
```
11:30:20.634Z ERROR lisk-framework: Failed to get transactions from network (module=lisk:app)
    RequestFailError: Request failed due to no peers found in peer selection
        at PeerPool.request (/Users/manu/lisk_ecosystem/sdk-core-lips/lisk-sdk/elements/lisk-p2p/dist-node/peer_pool.js:138:19)
        at P2P.request (/Users/manu/lisk_ecosystem/sdk-core-lips/lisk-sdk/elements/lisk-p2p/dist-node/p2p.js:292:47)
        at Network.request (/Users/manu/lisk_ecosystem/sdk-core-lips/lisk-sdk/framework/src/application/network/network.js:315:19)
```

### Acceptance Criteria

- There should not be any error on the startup regards to the network request
- It should successfully get transactions/signatures from other node

**Comment by shuse2** [comment]
Solved by #4802
