### ISSUE TITLE
Application errors during start

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4786]
### Expected behavior
If there are no peers available in peer pool, the network  should not fail with error, rather inform with message no peers found in peer pool.
### Actual behavior
```
11:30:20.634Z ERROR lisk-framework: Failed to get transactions from network (module=lisk:app)
    RequestFailError: Request failed due to no peers found in peer selection
        at PeerPool.request (/Users/manu/lisk_ecosystem/sdk-core-lips/lisk-sdk/elements/lisk-p2p/dist-node/peer_pool.js:138:19)
        at P2P.request (/Users/manu/lisk_ecosystem/sdk-core-lips/lisk-sdk/elements/lisk-p2p/dist-node/p2p.js:292:47)
        at Network.request (/Users/manu/lisk_ecosystem/sdk-core-lips/lisk-sdk/framework/src/application/network/network.js:315:19)
```
### Steps to reproduce
`LISK_CONSOLE_LOG_LEVEL=debug node framework/test/test_app | npx bunyan -o short -l info`
### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by shuse2** [comment]
Merged with #4785
