### ISSUE TITLE
Dev chain cannot restart after SIGTERM

### ISSUE THREAD

**Issue by ricott1** [LiskHQ/lisk-sdk#4885]
### Expected behavior
I should be able to stop the node with ^c and then restart it.

### Actual beahviour
After stopping a node using `^c` and trying to restart it, the following error is displayed, and the process exit:

```
15:17:29.835Z  INFO lisk-framework: Booting the application with Lisk Framework(0.1.0) (module=lisk-controller)
15:17:29.837Z  INFO lisk-framework: Starting the app - devnet-alpha-sdk (module=lisk-controller)
15:17:29.850Z  INFO lisk-framework: Initializing controller (module=lisk-controller)
15:17:29.857Z  INFO lisk-framework: Loading controller (module=lisk-controller)
15:17:29.927Z  INFO lisk-framework: Previous Lisk PID (module=lisk-controller)
15:17:29.927Z  INFO lisk-framework: Current Lisk PID (module=lisk-controller)
15:17:29.963Z  INFO lisk-framework-chain: Loading in-memory module (module=lisk-controller, version=0.1.0, moduleAlias=chain)
WARNING: Creating a duplicate database object for the same connection.
    at PgpAdapter.connect (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/components/storage/adapters/pgp_adapter.js:89:13)
    at Storage.bootstrap (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/components/storage/storage.js:40:23)
    at module.exports (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/init_steps/bootstrap_storage.js:42:32)
    at Chain.bootstrap (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/chain.js:133:10)
    at async ChainModule.load (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/index.js:139:3)
    at async Controller._loadInMemoryModule (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/controller/controller.js:212:3)
    at async Controller._loadModules (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/controller/controller.js:184:5)
    at async Controller.load (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/controller/controller.js:69:3)

15:17:29.985Z  INFO lisk-framework: Modules ready and launched (module=chain)
15:17:30.012Z FATAL lisk-framework: Failed to initialization chain module (module=chain)
    message: Number of rounds requested is higher than number of existing rounds.
    --
    stack: Error: Number of rounds requested is higher than number of existing rounds.
        at Dpos.getMinActiveHeightsOfDelegates (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/dpos/dpos.js:119:10)
        at async /Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/block_processor_v2.js:172:41
        at async Pipeline.run (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/processor/pipeline.js:55:18)
        at async Processor.init (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/processor/processor.js:73:4)
        at async Chain.bootstrap (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/chain.js:180:4)
        at async ChainModule.load (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/modules/chain/index.js:139:3)
        at async Controller._loadInMemoryModule (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/controller/controller.js:212:3)
        at async Controller._loadModules (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/controller/controller.js:184:5)
        at async Controller.load (/Users/alessandro.ricottone/Desktop/lisk-chess/node_modules/lisk-framework/src/controller/controller.js:69:3)
15:17:30.012Z  INFO lisk-framework: Cleanup controller... (module=lisk-controller)
15:17:30.013Z ERROR lisk-framework: Reason: Error: Number of rounds requested is higher than number of existing rounds. (module=lisk-controller)
15:17:30.014Z  INFO lisk-framework: Unload completed (module=lisk-controller)
15:17:30.014Z  INFO lisk-framework-chain: Loaded in-memory module (module=lisk-controller, version=0.1.0, moduleAlias=chain)
15:17:30.014Z  INFO lisk-framework: Shutting down application (module=lisk-controller, errorCode=0, message={})
15:17:30.014Z  INFO lisk-framework: Cleanup controller... (module=lisk-controller)
```

This error does not happen every time, but seemingly randomly. Dropping the `lisk_dev` database and recreating solves the issue :)

### Steps to reproduce

Launch the dev chain, stop it and then restart it.

### Which version(s) does this affect? (Environment, OS, etc...)
MacOS, using "lisk-sdk": "^3.0.2"

**Comment by shuse2** [comment]
This issue is fixed in 4.0.0
