### ISSUE TITLE
Endpoint /api/accounts is broken

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#4994]
### Expected behavior

Endpoint `/api/accounts` works correctly and return results

### Actual behavior

When calling `http://localhost:4000/api/accounts` I get the error: 

```
swagger:swagger_router exec +1ms
  swagger:swagger_router loading controller accounts from fs: [
  '/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/http_api/controllers'
] +0ms
  swagger:swagger_router controller found /Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/http_api/controllers/accounts +0ms
  swagger:swagger_router running controller, as pipe +0ms
  pipes exit fitting: swagger_router +1ms
  pipes caught error: TypeError: storage.entities.Account.get(...).map is not a function
    at AccountsController.getAccounts (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/http_api/controllers/accounts.js:87:69)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) +1ms
  pipes starting onError pipe +0ms
  pipes pre-flight fitting: lisk_error_handler +0ms
  pipes input: undefined +0ms
```

**Comment by pablitovicente** [comment]
Duplicate of #4983
