### ISSUE TITLE
P2P Error occurred during synchronisation

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#4996]
### Actual behavior
```
11:13:52.776Z  INFO lisk-framework: Starting synchronizer (module=lisk:app, blockId=7038921956761835336, height=42)
11:13:52.822Z  INFO lisk-framework: Triggering: BlockSynchronizationMechanism (module=lisk:app)
11:13:52.841Z ERROR lisk-framework: EVENT_MESSAGE_RECEIVED: Peer has been banned temporarily (module=lisk:app, peerId=undefined:undefined)
11:13:52.858Z  INFO lisk-framework: Applying penalty to peer and restarting synchronizer (module=lisk:app, peerId=167.172.32.114:5000)
    reason: No common block has been found between the chain and the targeted peer
11:13:52.942Z ERROR lisk-framework: Error occurred during synchronization. (module=lisk:app)
    Error: Peer not found: 167.172.32.114:5000
        at PeerPool.applyPenalty (/home/lisk/lisk-3.0.0-beta.0-ae560183c-6c8f00a-Linux-x86_64/node_modules/@liskhq/lisk-p2p/src/peer_pool.ts:638:10)
        at P2P.applyPenalty (/home/lisk/lisk-3.0.0-beta.0-ae560183c-6c8f00a-Linux-x86_64/node_modules/@liskhq/lisk-p2p/src/p2p.ts:523:18)
        at Network.applyPenalty (/home/lisk/lisk-3.0.0-beta.0-ae560183c-6c8f00a-Linux-x86_64/node_modules/lisk-framework/src/application/network/network.js:364:19)
        at Object.handler (/home/lisk/lisk-3.0.0-beta.0-ae560183c-6c8f00a-Linux-x86_64/node_modules/lisk-framework/src/application/application.js:464:39)
        at InMemoryChannel.invoke (/home/lisk/lisk-3.0.0-beta.0-ae560183c-6c8f00a-Linux-x86_64/node_modules/lisk-framework/src/controller/channels/in_memory_channel.js:72:37)
        at BlockSynchronizationMechanism._applyPenaltyAndRestartSync (/home/lisk/lisk-3.0.0-beta.0-ae560183c-6c8f00a-Linux-x86_64/node_modules/lisk-framework/src/application/node/synchronizer/base_synchronizer.js:37:22)
        at BlockSynchronizationMechanism.run (/home/lisk/lisk-3.0.0-beta.0-ae560183c-6c8f00a-Linux-x86_64/node_modules/lisk-framework/src/application/node/synchronizer/block_synchronization_mechanism.js:71:17)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
### Steps to reproduce
- Run two nodes
- Add seedPeers to connect each other
- Enable forging on one node and sync in another
### Which version(s) does this affect? (Environment, OS, etc...)
4.0.0-alpha.0

**Comment by shuse2** [comment]
Resolved by #5028 and #5026
