### ISSUE TITLE
Transaction is rejected during broadcast with no info

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#5114]
### Expected behavior

`lisk transaction:broadcast` should be able to broadcast, in case of error it should return more meaning error from the node

### Actual behavior

The below transaction is rejected but the error message doesn't give any idea about the error
```bash
./bin/run transaction:broadcast '{
        "id": "11290968189718369965",
        "type": 13,
        "senderPublicKey": "b2abc963b76fab65163b35372701049006c97cb589a1163c4d7c42c36eb581fb",
        "senderId": "7715036167861911539L",
        "nonce": "1",
        "fee": "10000000000",
        "signatures": [
                "d3844e5a900fc43464a8a41c7104a907bbd77ae1e9a46091007b5c22fbbbd723ffae09ce351eb5bde722696e6fd4004d79afb04488d738ed670434fd0ba7510d"
        ],
        "asset": {
                "votes": [
                        {
                                "delegateAddress": "16796830995384197764L",
                                "amount": "1000000000"
                        }
                ]
        }
}'

›   Error: Transaction was rejected with errors
```

on the API the response is,

```json
{
    "message": "Transaction was rejected with errors",
    "code": 409,
    "errors": {}
}
```

### Steps to reproduce

1. Create a transaction
2. Broadcast it using POST `http://localhost:4000/api/transactions` or using commander `lisk transaction:broadcast`

### Which version(s) does this affect? (Environment, OS, etc...)
`4.0.0`

**Comment by shuse2** [comment]
```
Error: Account with address = 16796830995384197764L does not exist
    at AccountStore.get (70_lisk/lisk-sdk/elements/lisk-chain/dist-node/state_store/account_store.js:47:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async VoteTransaction.applyAsset (70_lisk/lisk-sdk/elements/lisk-transactions/dist-node/13_vote_transaction.js:141:35)
    at async VoteTransaction.apply (/70_lisk/lisk-sdk/elements/lisk-transactions/dist-node/base_transaction.js:108:29)
    at async Array.<anonymous> (/70_lisk/lisk-sdk/elements/lisk-chain/dist-node/transactions/transactions_handlers.js:25:37)
    at async /70_lisk/lisk-sdk/elements/lisk-chain/dist-node/transactions/compose_transaction_steps.js:12:15
    at async TransactionPool.add (/70_lisk/lisk-sdk/elements/lisk-transaction-pool/dist-node/transaction_pool.js:74:39)
    at async Transport._receiveTransaction (/70_lisk/lisk-sdk/framework/src/application/node/transport/transport.js:404:23)
    at async Transport.handleEventPostTransaction (/70_lisk/lisk-sdk/framework/src/application/node/transport/transport.js:265:15)
    at async TransactionsController.postTransaction (/70_lisk/lisk-sdk/framework/src/modules/http_api/controllers/transactions.js:110:16)
```
