### ISSUE TITLE
Sync fails on the height 103

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5116]
### Expected behavior
It should successfully sync up with the node

### Actual behavior
```
18:43:57 ERROR lisk-framework: Block processing failed (module=lisk:app)
Message: Random seed can't be calculated earlier in a round. Wait till you pass middle of round. Current height: 1
 Trace: Error: Random seed can't be calculated earlier in a round. Wait till you pass middle of round. Current height: 1
    at Object.exports.generateRandomSeeds (/70_lisk/lisk-sdk/elements/lisk-dpos/dist-node/random_seed.js:65:15)
    at DelegatesInfo._update (/70_lisk/lisk-sdk/elements/lisk-dpos/dist-node/delegates_info.js:63:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Pipeline.run (/Users/stoda/Documents/70_lisk/lisk-sdk/framework/src/application/node/processor/pipeline.js:55:18)
    at async Processor._processValidated (/70_lisk/lisk-sdk/framework/src/application/node/processor/processor.js:315:3)
    at async Object.worker (/70_lisk/lisk-sdk/framework/src/application/node/processor/processor.js:187:4)
    at async Sequence._tick (/70_lisk/lisk-sdk/framework/src/application/node/utils/sequence.js:54:19)
    at async Timeout.nextSequence [as _onTimeout] (/70_lisk/lisk-sdk/framework/src/application/node/utils/sequence.js:41:4)
18:43:57 ERROR lisk-framework: Blocks temp table should not be empty (module=lisk:app)
```

### Steps to reproduce
Prepare 2 nodes and 1 node is forging all the blocks, and try to sync up with the node from scratch after 1000 blocks

But it seems it does not happen consistently

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

**Comment by shuse2** [comment]
This is invalid since it's caused by the local changes. 
However, #5110 should take care that it is expecting to be `height asc`
