### ISSUE TITLE
Possible issue in transaction ordering or test setup

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#5400]
### Expected behavior

Test does not fail randomly

### Actual behavior

- It seems the test `framework/test/integration/specs/application/node/processor/transaction_order.spec.ts` is failing sometimes.
- Only happens on Jenkins

Sample error output: 

```
[2020-06-05T14:01:34.829Z] FAIL test/integration/specs/application/node/processor/transaction_order.spec.ts

[2020-06-05T14:01:34.829Z]   Transaction order

[2020-06-05T14:01:34.829Z]     given transactions in specific order

[2020-06-05T14:01:34.829Z]       when account does not have sufficient balance at the beginning, but receives before spending

[2020-06-05T14:01:34.829Z]         ✓ should accept the block (5ms)

[2020-06-05T14:01:34.829Z]       when account register as delegate and make self vote

[2020-06-05T14:01:34.829Z]         ✓ should accept the block (1ms)

[2020-06-05T14:01:34.829Z]       when account register as multisignature and send from the accounts

[2020-06-05T14:01:34.829Z]         ✕ should accept the block (4ms)

[2020-06-05T14:01:34.829Z]       when account register as multisignature and send transfer with old signature

[2020-06-05T14:01:34.829Z]         ✓ should not accept the block (7ms)

[2020-06-05T14:01:34.829Z]       when account does not have sufficient balance in the middle of process

[2020-06-05T14:01:34.829Z]         ✓ should not accept the block (13ms)

[2020-06-05T14:01:34.829Z] 

[2020-06-05T14:01:34.829Z]   ● Transaction order › given transactions in specific order › when account register as multisignature and send from the accounts › should accept the block

[2020-06-05T14:01:34.829Z] 

[2020-06-05T14:01:34.829Z]     Failed: Array [

[2020-06-05T14:01:34.829Z]       [TransactionError: Optional keys should be sorted lexicographically],

[2020-06-05T14:01:34.829Z]     ]

[2020-06-05T14:01:34.829Z] 

[2020-06-05T14:01:34.829Z]       165 | 			let newBlock: Block;

[2020-06-05T14:01:34.829Z]       166 | 

[2020-06-05T14:01:34.829Z]     > 167 | 			beforeAll(async () => {

[2020-06-05T14:01:34.829Z]           | 			^

[2020-06-05T14:01:34.829Z]       168 | 				const genesisAccount = await node[

[2020-06-05T14:01:34.829Z]       169 | 					'_chain'

[2020-06-05T14:01:34.829Z]       170 | 				].dataAccess.getAccountByAddress(genesis.address);

[2020-06-05T14:01:34.829Z] 

[2020-06-05T14:01:34.829Z]       at Env.beforeAll (../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:41:24)

[2020-06-05T14:01:34.829Z]       at Suite.<anonymous> (test/integration/specs/application/node/processor/transaction_order.spec.ts:167:4)

[2020-06-05T14:01:34.829Z]       at Suite.<anonymous> (test/integration/specs/application/node/processor/transaction_order.spec.ts:164:3)

[2020-06-05T14:01:34.829Z] 

[2020-06-05T14:01:34.829Z]   ● Transaction order › given transactions in specific order › when account register as multisignature and send from the accounts › should accept the block

[2020-06-05T14:01:34.829Z] 

[2020-06-05T14:01:34.829Z]     Specified key blocks:id:Ýê¯·1+FÈÒÇzb4¶`í.OôN#G does not exist

[2020-06-05T14:01:34.829Z] 

[2020-06-05T14:01:34.829Z]       69 | 			// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access

[2020-06-05T14:01:34.829Z]       70 | 			if (error.notFound) {

[2020-06-05T14:01:34.829Z]     > 71 | 				throw new NotFoundError(key);

[2020-06-05T14:01:34.829Z]          | 				      ^

[2020-06-05T14:01:34.829Z]       72 | 			}

[2020-06-05T14:01:34.829Z]       73 | 			throw error;

[2020-06-05T14:01:34.829Z]       74 | 		}

[2020-06-05T14:01:34.829Z] 

[2020-06-05T14:01:34.829Z]       at KVStore.get (../elements/lisk-db/src/kv_store.ts:71:11)
```

### Steps to reproduce

Run a build on Jenkins until it fails though this is not really practical so probably checking the test setup first and then the code being tested could be better.

### Which version(s) does this affect? (Environment, OS, etc...)

development branch

**Comment by shuse2** [comment]
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/integration/specs/application/node/processor/transaction_order.spec.ts#L193
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/test/integration/specs/application/node/processor/transaction_order.spec.ts#L274
These two optional keys must be sorted otherwise it's invalid transaction
