### ISSUE TITLE
Synchronization should end successfully

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5486]
### Expected behavior
Block synchronization should end successfully

### Actual behavior
```
Message: The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined
 Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined
    at Uint8Array.equals (buffer.js:809:11)
    at Object.exports.isValidBlock (/lisk-sdk/elements/lisk-bft/src/fork_choice_rule.ts:46:15)
    at BFT.forkChoice (/lisk-sdk/elements/lisk-bft/src/bft.ts:136:22)
    at /lisk-sdk/framework/src/application/node/block_processor_v2.ts:140:20
    at Pipeline.run (/lisk-sdk/framework/src/application/node/processor/pipeline.ts:64:25)
    at Processor.forkStatus (/lisk-sdk/framework/src/application/node/processor/processor.ts:251:36)
    at BlockSynchronizationMechanism._computeBestPeer (/lisk-sdk/framework/src/application/node/synchronizer/block_synchronization_mechanism.ts:579:49)
    at BlockSynchronizationMechanism.run (/lisk-sdk/framework/src/application/node/synchronizer/block_synchronization_mechanism.ts:86:32)
    at Synchronizer.run (/lisk-sdk/framework/src/application/node/synchronizer/synchronizer.ts:138:25)
    at runMicrotasks (<anonymous>)
```

### Steps to reproduce
- One node forging all blocks
- Start another node from scratch wait for sync. 
- Stop the syncing node and wait for a while and start the node again

**Comment by shuse2** [comment]
It is failing because framework/src/application/node/synchronizer/block_synchronization_mechanism.ts:570
```
const peersTip = {
			id: Buffer.alloc(0),
			height: selectedPeers[randomPeerIndex].height,
			version: selectedPeers[randomPeerIndex].blockVersion,
			asset: {
				maxHeightPrevoted: selectedPeers[randomPeerIndex].maxHeightPrevoted,
			},
		};
```
peerTip does not have the previousBlockID, and fails with validBlock fork choice check
