### ISSUE TITLE
Node should restart without error

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5490]
### Expected behavior
When node is stopped and restarted, it should continue without error

### Actual behavior
In some condition, if a forging node is stopped and restarted, it shows below error and stop working
```
22:36:01 ERROR lisk-framework: Violation of the condition that delegate must choose the branch with largest maxHeightPrevoted (module=lisk:app)
Message: Violation of the condition that delegate must choose the branch with largest maxHeightPrevoted
 Trace: Error: Violation of the condition that delegate must choose the branch with largest maxHeightPrevoted
    at FinalityManager.verifyBlockHeaders (/lisk-sdk/elements/lisk-bft/src/finality_manager.ts:443:10)
    at BFT.verifyNewBlock (/lisk-sdk/elements/lisk-bft/src/bft.ts:116:31)
    at BlockProcessorV2.verify.pipe.async.block.block (//lisk-sdk/framework/src/application/node/block_processor_v2.ts:172:20)
    at Pipeline.run (//lisk-sdk/framework/src/application/node/processor/pipeline.ts:64:25)
    at Processor._processValidated (//lisk-sdk/framework/src/application/node/processor/processor.ts:348:3)
    at Object.worker (/lisk-sdk/framework/src/application/node/processor/processor.ts:240:4)
    at Sequence._tick (/lisk-sdk/framework/src/application/node/utils/sequence.ts:98:19)
    at Timeout.nextSequence [as _onTimeout] (/lisk-sdk/framework/src/application/node/utils/sequence.ts:63:4)

```

### Steps to reproduce
Restart the node which is forging

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

**Comment by shuse2** [comment]
`maxHeightPrevoted` obtained from the BFT when creating the block is returning `0`
