### ISSUE TITLE
While syncing it fails to process block because of maxHeightPrevoted

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5506]
### Expected behavior
With 2 local nodes without malicious code, it should successfully sync to each other

### Actual behavior
```
18:37:05 ERROR lisk-framework: Block processing failed (module=lisk:app)
Message: Wrong maxHeightPrevoted in blockHeader. maxHeightPrevoted: 344, : 447
 Trace: Error: Wrong maxHeightPrevoted in blockHeader. maxHeightPrevoted: 344, : 447
    at FinalityManager.verifyBlockHeaders (/lisk-sdk/elements/lisk-bft/src/finality_manager.ts:388:10)
    at BFT.verifyNewBlock (/lisk-sdk/elements/lisk-bft/src/bft.ts:116:31)
    at BlockProcessorV2.verify.pipe.async.block.block (/lisk-sdk/framework/src/application/node/block_processor_v2.ts:172:20)
    at Pipeline.run (/lisk-sdk/framework/src/application/node/processor/pipeline.ts:64:25)
    at Processor._processValidated (/lisk-sdk/framework/src/application/node/processor/processor.ts:348:3)
    at Sequence._tick (/lisk-sdk/framework/src/application/node/utils/sequence.ts:98:19)
    at Timeout.nextSequence [as _onTimeout] (/lisk-sdk/framework/src/application/node/utils/sequence.ts:63:4)
```

### Steps to reproduce
- Run a forging node and let it forge more than 1000 blocks
- From another node, Sync to the node from scratch 
- After a while it fails with above error

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

**Comment by shuse2** [comment]
This happens after reverting the block for synchronization.
It's highly possible that maxHeightPrevote cache is not being updated
