### ISSUE TITLE
Fail to reload temp blocks because of maxPrevoteHeight

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5507]
### Expected behavior
Once syncing fails, it should successfully reload from the temp blocks saved.
This issue could be related to #5506 

### Actual behavior
```
18:37:06 DEBUG lisk-framework: Restoring blocks from temporary table (module=lisk:app)
18:37:06 DEBUG lisk-framework: Processing validated block (module=lisk:app)
{
 "id": "eZ0wOFv+LzXc5cFXCGnxjXtuQK0PQtpS1t/qqKZqMEM=",
 "height": 515
}
18:37:06 ERROR lisk-framework: Failed to restore blocks from blocks temp table (module=lisk:app)
Message: Wrong maxHeightPrevoted in blockHeader. maxHeightPrevoted: 446, : 447
 Trace: Error: Wrong maxHeightPrevoted in blockHeader. maxHeightPrevoted: 446, : 447
    at FinalityManager.verifyBlockHeaders (/lisk-sdk/elements/lisk-bft/src/finality_manager.ts:388:10)
    at BFT.verifyNewBlock (/lisk-sdk/elements/lisk-bft/src/bft.ts:116:31)
    at BlockProcessorV2.verify.pipe.async.block.block (/lisk-sdk/framework/src/application/node/block_processor_v2.ts:172:20)
    at Pipeline.run (/lisk-sdk/framework/src/application/node/processor/pipeline.ts:64:25)
    at Processor._processValidated (/lisk-sdk/framework/src/application/node/processor/processor.ts:348:3)
    at Sequence._tick (/lisk-sdk/framework/src/application/node/utils/sequence.ts:98:19)
    at Timeout.nextSequence [as _onTimeout] (/lisk-sdk/framework/src/application/node/utils/sequence.ts:63:4)
```

### Steps to reproduce
Same as #5506 , and it happens after failing on the #5506 

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

**Comment by shuse2** [comment]
`framework/src/application/node/synchronizer/utils.ts:32`
In line32, it is applying the temp blocks, but `getTempBlocks` returns block in height:desc. Therefore, the temp blocks should be reversed or sorted
