### ISSUE TITLE
Fastchain switching fails to process block

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5698]
### Expected behavior
Syncing to valid node should not have block processing error.

### Actual behavior
```
08:58:57 ERROR lisk-framework: Error while processing blocks (module=lisk:app)
Message:
 Trace: BlockProcessingError
    at new SynchronizerError (node/v12.18.3/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/application/node/synchronizer/errors.js:4:1)
    at new BlockProcessingError (node/v12.18.3/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/application/node/synchronizer/errors.js:7:1)
    at FastChainSwitchingMechanism._applyBlocks (node/v12.18.3/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/application/node/synchronizer/fast_chain_switching_mechanism.js:146:19)
08:58:57 INFO lisk-framework: New block added to the chain (module=lisk:app)
{
 "id": "v31lTJdEGnMoyFh/u/aQH4/kAv3qEe8fpbOXjm6LLlg=",
 "height": 7892,
 "numberOfTransactions": 0
}

```

### Steps to reproduce
Sync with running node

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

**Comment by shuse2** [comment]
When `_getBlocksFromNetwork` fails, it catches error https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/application/node/synchronizer/fast_chain_switching_mechanism.ts#L142 and continues to process. However, `chunkOfBlocks` is empty and tries to destructure the header, which is undefined
