### ISSUE TITLE
Error occurred during synchronization

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#5742]
### Expected behavior

No error should occur during  synchronization

### Actual behavior
```
11:14:36 INFO lisk-framework: Triggering: BlockSynchronizationMechanism (module=lisk:app)
11:14:36 ERROR lisk-framework: Error occurred during synchronization. (module=lisk:app)
Message: Synchronizer is already running
 Trace: Error: Synchronizer is already running
    at Synchronizer.run (/usr/local/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/application/node/synchronizer/synchronizer.js:34:19)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/application/node/node.js:426:32)
    at EventEmitter.emit (events.js:315:20)
```
### Steps to reproduce

- Stop an start nodee

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

**Comment by shuse2** [comment]
Solved by #5812
