### ISSUE TITLE
Delegate without valid hash onion is unable to forge

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-sdk#5793]
### Expected behavior
Delegate without a valid hash onion or seed reveal CAN forge but is not rewarded if it does not miss last 2 rounds (current round+last round)

### Actual behavior
Delegate without any hash onion or seed reveal FAILS to forge
Delegate with a invalid(whose pre-image does not match the last used) hash onion FAILS to forge

```
ERROR lisk-framework: Invalid block reward: 0 expected: 500000000 (module=lisk:app)
Message: Invalid block reward: 0 expected: 500000000 
 Trace: Error: Invalid block reward: 0 expected: 500000000
    at BFT.verifyBlockHeader (~/lisk-sdk/elements/lisk-bft/src/bft.ts:102:10)
    at Processor._processValidated (~/lisk-sdk/framework/src/node/processor/processor.ts:347:3)
    at Object.worker (~/lisk-sdk/framework/src/node/processor/processor.ts:225:4)
    at JobQueue._tick (~/lisk-sdk/elements/lisk-utils/src/job_handlers/job_queue.ts:109:19)
    at Timeout.nextJobQueue [as _onTimeout] (~/lisk-sdk/elements/lisk-utils/src/job_handlers/job_queue.ts:62:4)
```

### Steps to reproduce

1. Change the config.json to alter the hash onions of a "particular delegate" to empty or random values
2. Run a node including the above config with forging disabled intially
3. Enable the "particular delegate" and optionally a few others to forge
4. Wait for atleast 2 rounds and check the console log

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

**Comment by ManuGowda** [comment]
Verified
```
17:29:36 WARN lisk-framework: Deducting reward due to SeedReveal violation (module=lisk:app)
{
 "originalReward": "125000000",
 "deductedReward": "0"
}
```
