### ISSUE TITLE
Error `Failed to restore blocks from blocks temp table` when starting fresh node

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#5807]
### Expected behavior

Should not see this error when starting network with fresh data. However the synching process works fine after the error.
This may be related to #5794 

### Actual behavior

Full error log:

```
11:09:46 INFO lisk-framework: Deleted a block from the chain (module=lisk:app)
{
 "id": "3f5b7b38b42d39a601d9f6a4af891b2df08d78783b4ebb005b79a8cc2295e47f",
 "height": 1
}
11:09:46 ERROR lisk-framework: Failed to restore blocks from blocks temp table (module=lisk:app)
Message: Can not delete block below or same as finalized height
 Trace: Error: Can not delete block below or same as finalized height
    at Processor._deleteBlock (/Users/mitsu/.nvm/versions/node/v12.18.2/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/node/processor/processor.js:313:19)
    at Object.worker (/Users/mitsu/.nvm/versions/node/v12.18.2/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/node/processor/processor.js:167:24)
    at JobQueue._tick (/Users/mitsu/.nvm/versions/node/v12.18.2/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-utils/dist-node/job_handlers/job_queue.js:61:39)
    at Timeout.nextJobQueue [as _onTimeout] (/Users/mitsu/.nvm/versions/node/v12.18.2/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-utils/dist-node/job_handlers/job_queue.js:24:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
11:09:46 INFO lisk-framework: Applying penalty to peer and restarting synchronizer (module=lisk:app)
{
 "peerId": "37.139.15.34:5000",
 "reason": "New tip of the chain has no preference over the previous tip before synchronizing"
}
11:09:46 ERROR lisk-framework: EVENT_MESSAGE_RECEIVED: Peer has been banned temporarily (module=lisk:app)
{
 "peerId": "37.139.15.34:5000"
}
11:09:46 INFO lisk-framework: Starting synchronizer (module=lisk:app)
{
 "blockId": "9b1bbedd26baa7670b4e9e1da17be02cdd4bf4491064f55d72be68eb8b0507c2",
 "height": 36523
}
11:09:46 ERROR lisk-framework: Error occurred during synchronization. (module=lisk:app)
Message: Apply penalty and restart synchronization mechanism with reason: New tip of the chain has no preference over the previous tip before synchronizing
 Trace: ApplyPenaltyAndRestartError: Apply penalty and restart synchronization mechanism with reason: New tip of the chain has no preference over the previous tip before synchronizing
    at new SynchronizerError (/Users/mitsu/.nvm/versions/node/v12.18.2/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/node/synchronizer/errors.js:4:1)
    at new ApplyPenaltyAndRestartError (/Users/mitsu/.nvm/versions/node/v12.18.2/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/node/synchronizer/errors.js:26:9)
    at BlockSynchronizationMechanism._handleBlockProcessingError (/Users/mitsu/.nvm/versions/node/v12.18.2/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/node/synchronizer/block_synchronization_mechanism.js:131:19)
11:09:46 INFO lisk-framework: Triggering: BlockSynchronizationMechanism (module=lisk:app)
11:09:55 INFO lisk-framework: New block added to the chain (module=lisk:app)
```

### Steps to reproduce
Clear existing blockchain data
Run fresh node on alpha network
Observe early logs at height 1 

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

**Comment by shuse2** [comment]
Solved by #5812
