### ISSUE TITLE
Stopping application shows error 

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#5830]
### Expected behavior
Child process should gracefully shutdown without error

### Actual behavior
```
12:35:37 INFO lisk-framework: Controller cleanup started (module=lisk:app)
12:35:37 ERROR lisk-framework: System error: uncaughtException (module=lisk:app)
Message: Cannot read property 'writable' of undefined
 Trace: TypeError: Cannot read property 'writable' of undefined
    at PubSocket.send (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/pm2-axon/lib/sockets/pub.js:47:14)
    at Bus.publish (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/controller/bus.js:115:29)
    at PullSocket.<anonymous> (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/controller/bus.js:51:18)
    at PullSocket.emit (events.js:315:20)
    at Parser.<anonymous> (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/pm2-axon/lib/sockets/sock.js:224:15)
    at Parser.emit (events.js:315:20)
    at Parser._write (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Parser.Writable.write (_stream_writable.js:318:11)
12:35:37 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 1,
 "message": "Cannot read property 'writable' of undefined"
}
```

### Steps to reproduce
Run plugins with child process and start and stop the application multiple times

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0-alpha.1

**Comment by shuse2** [comment]
#5831 updates the log to `debug` but the root problem still exists
