### ISSUE TITLE
Potential regression introduced on code or flaky tests

### ISSUE THREAD

**Issue by pablitovicente** [LiskHQ/lisk-sdk#5970]
### Expected behavior

- The `Lisk Framework Integration` pipeline do not randomly fail

### Actual behavior

- Pipeline randomly fails

### Steps to reproduce

- Build the project on Jenkins
- Check logs in the comments

### Which version(s) does this affect? (Environment, OS, etc...)

development branch

**Comment by pablitovicente** [comment]
`Lisk Framework Plugins Integration` random failure example: 

```
+ npx lerna run test:integration --scope=@liskhq/lisk-framework-*

lerna notice cli v3.22.1

lerna info versioning independent

lerna info ci enabled

lerna notice filter including "@liskhq/lisk-framework-*"

lerna info filter [ '@liskhq/lisk-framework-*' ]

lerna info Executing command in 1 package: "yarn run test:integration"

@liskhq/lisk-framework-report-misbehavior-plugin: yarn run v1.22.4

@liskhq/lisk-framework-report-misbehavior-plugin: $ jest --config=./test/integration/jest.config.js --runInBand

@liskhq/lisk-framework-report-misbehavior-plugin: PASS test/integration/db.spec.ts (11.79 s)

@liskhq/lisk-framework-report-misbehavior-plugin: FAIL test/integration/cleanup_job.spec.ts

@liskhq/lisk-framework-report-misbehavior-plugin:   ● Clean up old blocks › should clear old blockheaders

@liskhq/lisk-framework-report-misbehavior-plugin:     expect(received).rejects.toThrow()

@liskhq/lisk-framework-report-misbehavior-plugin:     Received promise resolved instead of rejected

@liskhq/lisk-framework-report-misbehavior-plugin:     Resolved to value: {"data": [10, 212, 1, 8, 2, 16, 128, 137, 122, 24, 160, 247, 54, 34, 32, 150, 150, 52, 46, 211, 85, 132, 139, 76, 214, 215, 199, 112, 147, 18, 26, 227, 252, 16, 244, 73, 68, 127, 65, 4, 73, 114, 23, 78, 117, 188, 43, 42, 32, 227, 176, 196, 66, 152, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185, 36, 39, 174, 65, 228, 100, 155, 147, 76, 164, 149, 153, 27, 120, 82, 184, 85, 50, 32, 173, 219, 14, 21, 164, 75, 15, 220, 111, 242, 145, 190, 40, 216, 201, 143, 85, 81, 208, 205, 146, 24, 215, 73, 227, 13, 219, 135, 198, 227, 28, 169, 56, 128, 200, 175, 160, 37, 66, 26, 8, 208, 142, 42, 16, 224, 220, 42, 26, 16, 200, 197, 87, 181, 219, 168, 82, 124, 14, 118, 1, 36, 18, 143, 209, 92, 74, 64, 86, 180, 18, 170, 37, 196, 158, 92, 60, 201, 114, 87, 151, 34, 73, 253, 10, 214, 95, 142, 67, 18, 100, 217, 192, 75, 99, 155, 70, 176, 131, 155, 1, 174, 141, 35, 154, 53, 71, 152, 186, 225, 135, 60, 131, 24, 162, 94, 246, 26, 141, 201, 199, 160, 152, 45, 161, 122, 251, 36, 251, 225, 92, 5], "type": "Buffer"}

@liskhq/lisk-framework-report-misbehavior-plugin:       124 | 		);

@liskhq/lisk-framework-report-misbehavior-plugin:       125 | 		await new Promise(resolve => setTimeout(resolve, 100));

@liskhq/lisk-framework-report-misbehavior-plugin:     > 126 | 		await expect((reportMisbehaviorPlugin as any)._pluginDB.get(dbKey)).rejects.toThrow(

@liskhq/lisk-framework-report-misbehavior-plugin:           | 		      ^

@liskhq/lisk-framework-report-misbehavior-plugin:       127 | 			`Specified key ${dbKey} does not exist`,

@liskhq/lisk-framework-report-misbehavior-plugin:       128 | 		);

@liskhq/lisk-framework-report-misbehavior-plugin:       129 | 	});

@liskhq/lisk-framework-report-misbehavior-plugin:       at expect (../../node_modules/expect/build/index.js:134:15)

@liskhq/lisk-framework-report-misbehavior-plugin:       at Object.<anonymous> (test/integration/cleanup_job.spec.ts:126:9)

@liskhq/lisk-framework-report-misbehavior-plugin: Test Suites: 1 failed, 1 passed, 2 total

@liskhq/lisk-framework-report-misbehavior-plugin: Tests:       1 failed, 3 passed, 4 total

@liskhq/lisk-framework-report-misbehavior-plugin: Snapshots:   0 total

@liskhq/lisk-framework-report-misbehavior-plugin: Time:        14.361 s

@liskhq/lisk-framework-report-misbehavior-plugin: Ran all test suites.

@liskhq/lisk-framework-report-misbehavior-plugin: error Command failed with exit code 1.

@liskhq/lisk-framework-report-misbehavior-plugin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test:integration exited 1 in '@liskhq/lisk-framework-report-misbehavior-plugin'

script returned exit code 1

**Comment by pablitovicente** [comment]
`Lisk Framework Integration` random failure example: 

```
[2020-11-12T12:07:56.603Z] + npm run test:integration

[2020-11-12T12:07:56.603Z] 

[2020-11-12T12:07:56.603Z] > lisk-framework@0.7.0-alpha.3 test:integration /home/lisk/workspace/lisk-sdk_PR-5969/framework

[2020-11-12T12:07:56.603Z] > jest --config=./test/integration/jest.config.js

[2020-11-12T12:07:56.603Z] 

[2020-11-12T12:08:00.793Z] PASS test/integration/controller/ipc/ipc_server.spec.ts

[2020-11-12T12:08:00.793Z] PASS test/integration/controller/ipc_channel_without_bus.spec.ts

[2020-11-12T12:08:00.793Z] PASS test/integration/controller/in_memory_channel.spec.ts

[2020-11-12T12:08:01.053Z] PASS test/integration/controller/ipc_channel.spec.ts

[2020-11-12T12:08:01.622Z] PASS test/integration/node/forger/transaction_pool.spec.ts

[2020-11-12T12:08:01.881Z] PASS test/integration/node/processor/transaction_order.spec.ts

[2020-11-12T12:08:01.881Z] PASS test/integration/node/genesis_block.spec.ts

[2020-11-12T12:08:02.820Z] PASS test/integration/controller/ipc/ipc_client.spec.ts

[2020-11-12T12:08:03.755Z] PASS test/integration/node/processor/delete_block.spec.ts

[2020-11-12T12:08:13.726Z] FAIL test/integration/node/processor/process_block.spec.ts (13.135 s)

[2020-11-12T12:08:13.726Z]   ● Process block › given a block with invalid properties › when block has tie break BFT properties › should replace the last block

[2020-11-12T12:08:13.726Z] 

[2020-11-12T12:08:13.726Z]     Invalid block reward: 0 expected: 125000000

[2020-11-12T12:08:13.726Z] 

[2020-11-12T12:08:13.726Z]       100 | 		const expectedReward = isCompliant ? reward : reward / BigInt(4);

[2020-11-12T12:08:13.726Z]       101 | 		if (blockHeader.reward !== expectedReward) {

[2020-11-12T12:08:13.726Z]     > 102 | 			throw new Error(

[2020-11-12T12:08:13.726Z]           | 			      ^

[2020-11-12T12:08:13.726Z]       103 | 				`Invalid block reward: ${blockHeader.reward.toString()} expected: ${expectedReward.toString()}`,

[2020-11-12T12:08:13.726Z]       104 | 			);

[2020-11-12T12:08:13.726Z]       105 | 		}

[2020-11-12T12:08:13.726Z] 

[2020-11-12T12:08:13.726Z]       at BFT.verifyBlockHeader (../elements/lisk-bft/src/bft.ts:102:10)

[2020-11-12T12:08:13.726Z]       at Processor._processValidated (src/node/processor/processor.ts:347:3)

[2020-11-12T12:08:13.726Z]       at src/node/processor/processor.ts:214:6

[2020-11-12T12:08:13.726Z]       at Mutex.runExclusive (../elements/lisk-utils/src/job_handlers/mutex.ts:37:11)

[2020-11-12T12:08:13.726Z]       at Processor.process (src/node/processor/processor.ts:126:3)

[2020-11-12T12:08:13.726Z]       at Object.<anonymous> (test/integration/node/processor/process_block.spec.ts:367:5)

[2020-11-12T12:08:13.726Z] 

[2020-11-12T12:08:15.101Z] PASS test/integration/node/synchronizer/temp_block.spec.ts (15.688 s)

[2020-11-12T12:08:15.362Z] 

[2020-11-12T12:08:15.362Z] Test Suites: 1 failed, 10 passed, 11 total

[2020-11-12T12:08:15.362Z] Tests:       1 failed, 66 passed, 67 total

[2020-11-12T12:08:15.362Z] Snapshots:   1 passed, 1 total

[2020-11-12T12:08:15.362Z] Time:        17.245 s, estimated 23 s

[2020-11-12T12:08:15.362Z] Ran all test suites.

[2020-11-12T12:08:15.362Z] npm ERR! code ELIFECYCLE

[2020-11-12T12:08:15.362Z] npm ERR! errno 1

[2020-11-12T12:08:15.362Z] npm ERR! lisk-framework@0.7.0-alpha.3 test:integration: `jest --config=./test/integration/jest.config.js`

[2020-11-12T12:08:15.362Z] npm ERR! Exit status 1

[2020-11-12T12:08:15.362Z] npm ERR! 

[2020-11-12T12:08:15.362Z] npm ERR! Failed at the lisk-framework@0.7.0-alpha.3 test:integration script.

[2020-11-12T12:08:15.362Z] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

[2020-11-12T12:08:15.362Z] 

[2020-11-12T12:08:15.362Z] npm ERR! A complete log of this run can be found in:

[2020-11-12T12:08:15.362Z] npm ERR!     /home/lisk/.npm/_logs/2020-11-12T12_08_15_196Z-debug.log

script returned exit code 1

**Comment by mitsuaki-u** [comment]
This test will be handled in https://github.com/LiskHQ/lisk-sdk/issues/5977
