### ISSUE TITLE
Report Misbehavior plugin integration test fails on Jenkins

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk-sdk#5977]
### Expected behavior

Integration test for PoM plugin should pass on jenkins.

### Actual behavior

Randomly and inconsistently fails.

### Steps to reproduce

- Build the project on Jenkins
- Check logs in the comments

### Which version(s) does this affect? (Environment, OS, etc...)

5.1

**Comment by mitsuaki-u** [comment]
```
+ npx lerna run test:integration --scope=@liskhq/lisk-framework-*

lerna notice cli v3.22.1

lerna info versioning independent

lerna info ci enabled

lerna notice filter including "@liskhq/lisk-framework-*"

lerna info filter [ '@liskhq/lisk-framework-*' ]

lerna info Executing command in 1 package: "yarn run test:integration"

@liskhq/lisk-framework-report-misbehavior-plugin: yarn run v1.22.4

@liskhq/lisk-framework-report-misbehavior-plugin: $ jest --config=./test/integration/jest.config.js --runInBand

@liskhq/lisk-framework-report-misbehavior-plugin: PASS test/integration/db.spec.ts (11.79 s)

@liskhq/lisk-framework-report-misbehavior-plugin: FAIL test/integration/cleanup_job.spec.ts

@liskhq/lisk-framework-report-misbehavior-plugin:   ● Clean up old blocks › should clear old blockheaders

@liskhq/lisk-framework-report-misbehavior-plugin:     expect(received).rejects.toThrow()

@liskhq/lisk-framework-report-misbehavior-plugin:     Received promise resolved instead of rejected

@liskhq/lisk-framework-report-misbehavior-plugin:     Resolved to value: {"data": [10, 212, 1, 8, 2, 16, 128, 137, 122, 24, 160, 247, 54, 34, 32, 150, 150, 52, 46, 211, 85, 132, 139, 76, 214, 215, 199, 112, 147, 18, 26, 227, 252, 16, 244, 73, 68, 127, 65, 4, 73, 114, 23, 78, 117, 188, 43, 42, 32, 227, 176, 196, 66, 152, 252, 28, 20, 154, 251, 244, 200, 153, 111, 185, 36, 39, 174, 65, 228, 100, 155, 147, 76, 164, 149, 153, 27, 120, 82, 184, 85, 50, 32, 173, 219, 14, 21, 164, 75, 15, 220, 111, 242, 145, 190, 40, 216, 201, 143, 85, 81, 208, 205, 146, 24, 215, 73, 227, 13, 219, 135, 198, 227, 28, 169, 56, 128, 200, 175, 160, 37, 66, 26, 8, 208, 142, 42, 16, 224, 220, 42, 26, 16, 200, 197, 87, 181, 219, 168, 82, 124, 14, 118, 1, 36, 18, 143, 209, 92, 74, 64, 86, 180, 18, 170, 37, 196, 158, 92, 60, 201, 114, 87, 151, 34, 73, 253, 10, 214, 95, 142, 67, 18, 100, 217, 192, 75, 99, 155, 70, 176, 131, 155, 1, 174, 141, 35, 154, 53, 71, 152, 186, 225, 135, 60, 131, 24, 162, 94, 246, 26, 141, 201, 199, 160, 152, 45, 161, 122, 251, 36, 251, 225, 92, 5], "type": "Buffer"}

@liskhq/lisk-framework-report-misbehavior-plugin:       124 | 		);

@liskhq/lisk-framework-report-misbehavior-plugin:       125 | 		await new Promise(resolve => setTimeout(resolve, 100));

@liskhq/lisk-framework-report-misbehavior-plugin:     > 126 | 		await expect((reportMisbehaviorPlugin as any)._pluginDB.get(dbKey)).rejects.toThrow(

@liskhq/lisk-framework-report-misbehavior-plugin:           | 		      ^

@liskhq/lisk-framework-report-misbehavior-plugin:       127 | 			`Specified key ${dbKey} does not exist`,

@liskhq/lisk-framework-report-misbehavior-plugin:       128 | 		);

@liskhq/lisk-framework-report-misbehavior-plugin:       129 | 	});

@liskhq/lisk-framework-report-misbehavior-plugin:       at expect (../../node_modules/expect/build/index.js:134:15)

@liskhq/lisk-framework-report-misbehavior-plugin:       at Object.<anonymous> (test/integration/cleanup_job.spec.ts:126:9)

@liskhq/lisk-framework-report-misbehavior-plugin: Test Suites: 1 failed, 1 passed, 2 total

@liskhq/lisk-framework-report-misbehavior-plugin: Tests:       1 failed, 3 passed, 4 total

@liskhq/lisk-framework-report-misbehavior-plugin: Snapshots:   0 total

@liskhq/lisk-framework-report-misbehavior-plugin: Time:        14.361 s

@liskhq/lisk-framework-report-misbehavior-plugin: Ran all test suites.

@liskhq/lisk-framework-report-misbehavior-plugin: error Command failed with exit code 1.

@liskhq/lisk-framework-report-misbehavior-plugin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test:integration exited 1 in '@liskhq/lisk-framework-report-misbehavior-plugin'

script returned exit code 1

**Comment by mitsuaki-u** [comment]
This issue originally reported in #5970 was not reproducible. Closing issue.
