### ISSUE TITLE
Initial Install Errors

### ISSUE THREAD

**Issue by benjamin-martinez** [LiskHQ/lisk-sdk#6212]
Hello, 

I'm going through the QuickStart process listed in the docs. Everything is easy enough to install and set up, but once I run " node index.js", I get an error:

```
benjaminmartinez@Benjamins-Mac-mini liskTest % node index.js
18:36:13 INFO lisk-framework: Starting the app - devnet (module=lisk:app)
18:36:13 INFO lisk-framework: If you experience any type of error, please open an issue on Lisk GitHub: https://github.com/LiskHQ/lisk-sdk/issues (module=lisk:app)
18:36:13 INFO lisk-framework: Contribution guidelines can be found at Lisk-sdk: https://github.com/LiskHQ/lisk-sdk/blob/development/docs/CONTRIBUTING.md (module=lisk:app)
18:36:13 INFO lisk-framework: Booting the application with Lisk Framework(2.1.0) (module=lisk:app)
Faced error in application TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (50121)
    at writeFile (fs.js:1436:5)
    at go$writeFile (/Users/benjaminmartinez/Documents/Blockchain Stuff/liskTest/node_modules/graceful-fs/graceful-fs.js:139:14)
    at Object.writeFile (/Users/benjaminmartinez/Documents/Blockchain Stuff/liskTest/node_modules/graceful-fs/graceful-fs.js:136:12)
    at /Users/benjaminmartinez/Documents/Blockchain Stuff/liskTest/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/Users/benjaminmartinez/Documents/Blockchain Stuff/liskTest/node_modules/universalify/index.js:7:14)
    at Application._validatePidFile (/Users/benjaminmartinez/Documents/Blockchain Stuff/liskTest/node_modules/lisk-framework/dist-node/application.js:304:18)
    at async Application.run (/Users/benjaminmartinez/Documents/Blockchain Stuff/liskTest/node_modules/lisk-framework/dist-node/application.js:123:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}
18:36:13 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 1,
 "message": "process.exit"
} 
```

With the main line being: 
`Faced error in application TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (50121)`

This is a fresh install of disk on a fresh install of node/npm and on a brand new mac. Is this a problem anyone has seen before?

**Comment by shuse2** [comment]
This will be resolved in #6552
