### ISSUE TITLE
P2P functional test is unstable

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#6357]
### Expected behavior
- elements/lisk-p2p/test/functional/blacklist_whitelist_fixed_peers.spec.ts
- elements/lisk-p2p/test/functional/actions/request.spec.ts

should be stable

### Actual behavior
```
 FAIL  test/functional/actions/request.spec.ts
  ● P2P.request › requests made to the network should be distributed randomly

    expect(received).toBeGreaterThan(expected)

    Expected: > 100
    Received:   56

      94 |                      expect(requestsHandled).toEqual(expect.any(Array));
      95 |
    > 96 |                      expect(requestsHandled.length).toBeGreaterThan(expectedRequestsLowerBound);
         |                                                     ^
      97 |                      expect(requestsHandled.length).toBeLessThan(expectedRequestsUpperBound);
      98 |              }
      99 |      });

      at Object.<anonymous> (test/functional/actions/request.spec.ts:96:35)
          at runMicrotasks (<anonymous>)
```
```
 FAIL  test/functional/blacklist_whitelist_fixed_peers.spec.ts (21.792 s)
  ● Blacklisted/fixed/whitelisted peers › whitelisting › should allow connection from whitelisted peer even when incoming slots are full

    expect(received).toContain(expected) // indexOf

    Expected value: "127.0.0.10"
    Received array: ["127.0.0.12", "127.0.0.15", "127.0.0.13", "127.0.0.14", "127.0.0.19", "127.0.0.17", "127.0.0.16", "127.0.0.25", "127.0.0.18"]

      353 |
      354 |                     // Whitelisted first node should be able to connect back to second node even when the slot is full
    > 355 |                     expect(secondNode.getConnectedPeers().map(p => p.ipAddress)).toContain(
          |                                                                                  ^
      356 |                             firstWhitelistNode.config.hostIp,
      357 |                     );
      358 |             });

      at Object.<anonymous> (test/functional/blacklist_whitelist_fixed_peers.spec.ts:355:65)
```

### Steps to reproduce
cd elements/lisk-p2p
npm run enableLocalIPs
npm run test:functional

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by mitsuaki-u** [comment]
After investigation the test was found to be unstable due to variations occuring when running the test on jenkins. Through manual testing it was found that the whitelisted peers were not being evicted. Regarding the `request` test, some variance in distribution is to be expected.

**Comment by shuse2** [comment]
Closing this issue since this is no longer valid
