### ISSUE TITLE
Lisk Commander Bootstrapping is broken 

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#6372]
### Expected behavior

The Lisk-Commander command for bootstrapping should create application skeleton. 

### Actual behavior

Currently the bootstraping is broken. 

```
(node:56414) UnhandledPromiseRejectionWarning: TypeError: this.installDependencies is not a function
    at InitGenerator.install (/lisk-sdk/commander/src/bootstrapping/generators/init_generator.ts:42:8)
    at Object.<anonymous> (/lisk-sdk/node_modules/yeoman-generator/lib/index.js:1009:25)
    at /lisk-sdk/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
```

Probably its because of recent dependencies upgrade. 

```
yeoman-environment
2.10.3 -> 3.2.0

yeoman-generator
4.12.0 -> 5.2.0
```

### Steps to reproduce

```bash
cd lisk-commander
./bin/run init /path/to/project
```

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by nazarhussain** [comment]
This is the probable cause https://github.com/yeoman/generator/issues/1293
