### ISSUE TITLE
Bootstrap application linting is broken

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk-sdk#6376]
### Expected behavior

After we bootstrap the application `lisk init` and then run the `npm run lint`, the linting should work fine. 

### Actual behavior

Linting at the bootstrap application is broken

```
> npm run lint

> lisk-name-service@0.1.0 lint /my/app
> eslint --ext .js,.ts .


Oops! Something went wrong! :(

ESLint: 7.22.0

Error: Cannot read config file: /my/app/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /my/app/.eslintrc.js
    at Object.<anonymous> (/my/app/node_modules/eslint-config-prettier/@typescript-eslint.js:1:69)
    at Module._compile (/my/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at module.exports (/my/app/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/my/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:225:16)
    at loadConfigFile (/my/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:309:20)
    at ConfigArrayFactory._loadConfigData (/my/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:42)
```

### Steps to reproduce

```
lisk init /path/to/app
cd /path/to/app
npm run lint
```

### Which version(s) does this affect? (Environment, OS, etc...)
development

**Comment by nazarhussain** [comment]
After fixing this error. There are more linting errors: 

```
/my/app/.eslintrc.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided


/my/app/src/commands/genesis-block/create.ts
  7:24  error  Expected 'this' to be used by class method 'getApplication'  class-methods-use-this

/my/app/src/commands/start.ts
  136:32  error  Expected 'this' to be used by class method 'getApplicationConfigDir'  class-methods-use-this

/my/app/src/commands/transaction/create.ts
  11:2   error  Unsafe assignment of an any value            @typescript-eslint/no-unsafe-assignment
  12:6   error  Unsafe member access .flags on an any value  @typescript-eslint/no-unsafe-member-access
  15:17  error  Unsafe spread of an any value in an array    @typescript-eslint/no-unsafe-assignment
  15:20  error  Unsafe member access .args on an any value   @typescript-eslint/no-unsafe-member-access

/my/app/src/commands/transaction/sign.ts
   9:2   error  Unsafe assignment of an any value            @typescript-eslint/no-unsafe-assignment
  10:6   error  Unsafe member access .flags on an any value  @typescript-eslint/no-unsafe-member-access
  13:17  error  Unsafe spread of an any value in an array    @typescript-eslint/no-unsafe-assignment
  13:20  error  Unsafe member access .args on an any value   @typescript-eslint/no-unsafe-member-access

/my/app/test/.eslintrc.js
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided

/my/app/test/utils/config.ts
  5:26  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

```
