### ISSUE TITLE
Request timed out when calling application endpoints 

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-sdk#6579]
### Expected behavior

Ideally endpoints should respond within defined timeout, in worst case 3 seconds time out limit and best case 100ms to 500ms.
 
### Actual behavior

- Lisk Service is receiving timeout while calling certain application endpoints.
- Following are the endpoints which has performance bottleneck (taking more than 1sec and in worst case 10sec)
```
getNodeInfo
getLegacyAccountInfo
getAccounts
```

### Steps to reproduce

- Run Lisk Core blockchain with migrated Mainnet data
- Run Lisk Service integrated to Lisk Core
- Observe Lisk Service logs for timeouts

### Which version(s) does this affect? (Environment, OS, etc...)
5.1.1

**Comment by ManuGowda** [comment]
`getNodeInfo` timeout logs:
```
(node:1) UnhandledPromiseRejectionWarning: TimeoutException: Request timed out when calling 'getNetworkStatus'
    at Object.getNetworkStatus (/home/lisk/lisk-service/core/shared/core/compat/sdk_v5/coreApi.js:39:10)
```
`getAccountByAddress` timeout:
```
2021-07-14T13:27:32.931 ERROR [blocks] Request timed out when calling 'getAccountByAddress' for address: 000000000000000020dc2891220e179abc611af6
```

`getLegacyAccountInfo` timeout:
```
TimeoutException: Request timed out when calling 'getLegacyAccountInfo' for publicKey: 10cfee91b312a3de13d227dce3fa4af41946352509e426f492439038e4fc8571
    at Object.getLegacyAccountInfo (/home/lisk/lisk-service/core/shared/core/compat/sdk_v5/coreApi.js:198:10)
```

Other logs:
```
2021-07-14T13:28:03.531 WARN [queue] indexBlocksQueue Job failed,Request timed out when calling 'getAccountByAddress' for address: 6d04fd849f0a620a594ff122de3f600553e5e767
2021-07-14T13:28:03.531 WARN [queue] indexBlocksQueue Job failed,TimeoutException: Request timed out when calling 'getAccountByAddress' for address: 6d04fd849f0a620a594ff122de3f600553e5e767
    at Object.getAccountByAddress (/home/lisk/lisk-service/core/shared/core/compat/sdk_v5/coreApi.js:170:10)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
2021-07-14T13:28:03.554 WARN [blocks] Unable to update block index
2021-07-14T13:28:03.732 WARN [queue] indexBlocksQueue Job failed,Request timed out when calling 'getAccountByAddress' 
for address: 72c987a9308af8d07a8553e82f958521217c0929
    at Object.getAccountByAddress (/home/lisk/lisk-service/core/shared/core/compat/sdk_v5/coreApi.js:170:10)
```

**Comment by shuse2** [comment]
Closing because this is not the problem that we tend to cover now with lisk-sdk
The main issue was that the frequent API request used the server resource, and was not able to respond on time.

We might consider rate limiting in the future improvement.
