### ISSUE TITLE
Key not found error when posting a transaction

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#7258]
### Expected behavior

When we submit a valid transaction it should be accepted

### Actual behavior

When we post a transaction then we get the following error 

```bash
18:17:03 ERROR lisk-framework: Fail to respond (module=lisk:app)
Message: Key 000000020000b018f20e46db0768420a4c8837df15a30f3c58680000000000000000 does not exist.
 Trace: Error: Key 000000020000b018f20e46db0768420a4c8837df15a30f3c58680000000000000000 does not exist.
    at /lisk-repos/core/lisk-core/node_modules/@liskhq/lisk-db/state_db.js:111:39
{
 "method": "executeTransaction"
}
18:17:03 INFO lisk-framework: Generated new block (module=engine)
{
 "id": "4ac24fa869c1ec9009f248cb3f12cdc8aa54952022211de5d44e947c8983f10f",
 "height": 217,
 "generatorAddress": "f874da3cd4d7baef5c6f676eae6d8c7daa23e951"
}
18:17:03 ERROR lisk-framework: Fail to respond (module=lisk:app)
Message: Invalid state root `Not matching with expected`
 Trace: Error: Invalid state root `Not matching with expected`
{
 "method": "commit"
}
/lisk-repos/core/lisk-core/node_modules/lisk-framework/dist-node/abi_handler/abi_client.js:141
                deferred.reject(new Error(response.error.message));
                                ^

Error: Invalid state root `Not matching with expected`
    at ABIClient._listenToRPCResponse (/lisk-repos/core/lisk-core/node_modules/lisk-framework/dist-node/abi_handler/abi_client.js:141:33)
18:17:03 ERROR lisk-framework: Engine exited unexpectedly (module=lisk:app)
{
 "code": 1,
 "signal": ""
}
18:17:03 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 1,
 "message": "process.exit"
}
```

### Steps to reproduce

1. Run a node
2. Create a valid transaction using lisk-core command

```bash
./bin/run transaction:create 2 0 100000000 --params='{"amount":100000000,"recipientAddress":"c4c1c317001511c86d7faff93359d372c4e330f5","data":"send token", "tokenID": "0000000100000000"}'
```
3. Send the transaction using lisk-core command
```bash
./bin/run transaction:send "0802100018002080c2d72f2a2097831829cd9a692935f1bea380bcde108e6dfb8a95a481b220b2709f2c3513c032310a0800000001000000001080c2d72f1a14c4c1c317001511c86d7faff93359d372c4e330f5220a73656e6420746f6b656e3a40c35d2644cb945f3ff35a487d111d46e31fea7f11a0050ff06902c5266e705f569cc0761ecc59d19835c4f5fd50f6c60e5ba8af4a2cae299b82e19791237de507"
```

### Which version(s) does this affect? (Environment, OS, etc...)

`6.0.0-alpha.0`

**Comment by ishantiw** [comment]
Somewhere it is related to [dpos_getAllDelegates returns empty response #7239](https://github.com/LiskHQ/lisk-sdk/issues/7239) and [Add and expose interoperability APIs  #7261](https://github.com/LiskHQ/lisk-sdk/issues/7261)

**Comment by ishantiw** [comment]
Since there is no state initialization for Interoperability module, it fails at getting ownChainAccount. State initialization will be solved in https://github.com/LiskHQ/lisk-sdk/issues/7321 and then this bug needs to be tested again.

**Comment by ishantiw** [comment]
Now we are able to post transfer transactions which are able to get included in the block without key not found error. Solved in multiple issues,
#7299 
#7353
#7321
