### ISSUE TITLE
Node crashes when reward module fails to execute `afterTransactionsExecute`

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#7328]
### Expected behavior
* Reward module should use tokenID of length 8
* even if it fails, it should not crash the node

### Actual behavior

```
09:53:17 ERROR lisk-framework: Fail to respond (module=lisk:app)
Message: Token ID must have length 8
 Trace: Error: Token ID must have length 8
    at Object.splitTokenID (/Documents/10_lisk/lisk-sdk-review/framework/src/modules/token/utils.ts:31:9)
    at TokenAPI.getCanonicalTokenID (/Documents/10_lisk/lisk-sdk-review/framework/src/modules/token/api.ts:591:21)
    at TokenAPI.mint (/Documents/10_lisk/lisk-sdk-review/framework/src/modules/token/api.ts:189:39)
    at RewardModule.afterTransactionsExecute (/Documents/10_lisk/lisk-sdk-review/framework/src/modules/reward/module.ts:102:24)
    at StateMachine.afterExecuteBlock (/Documents/10_lisk/lisk-sdk-review/framework/src/state_machine/state_machine.ts:247:5)
    at ABIHandler.afterTransactionsExecute (/Documents/10_lisk/lisk-sdk-review/framework/src/abi_handler/abi_handler.ts:387:3)
    at ABIServer._listenToRequest (/Documents/10_lisk/lisk-sdk-review/framework/src/abi_handler/abi_server.ts:198:18)
{
 "method": "afterTransactionsExecute"
}
/Documents/10_lisk/lisk-sdk-review/framework/dist-node/abi_handler/abi_client.js:141
                deferred.reject(new Error(response.error.message));
                                ^

Error: Token ID must have length 8
    at ABIClient._listenToRPCResponse (/Documents/10_lisk/lisk-sdk-review/framework/dist-node/abi_handler/abi_client.js:141:33)
09:53:17 ERROR lisk-framework: Engine exited unexpectedly (module=lisk:app)
{
 "code": 1,
 "signal": ""
}
09:53:17 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 1,
 "message": "process.exit"
}

```
### Steps to reproduce
Run a node to the point where reward starts (height 2197 by default)
Reward offset can be updated to `100` or similar value to reproduce this error quicker

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.0

**Comment by milenagojkovic** [comment]
Closing issue as it was resolved in sprint 74, with PR https://github.com/LiskHQ/lisk-sdk/pull/735. Moving to Milestone 74.
