### ISSUE TITLE
CLI fails with error upon non existing transaction ID

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7480]
### Expected behavior
It should return correct error message, e.g. `transaction not found for given ID`

### Actual behavior
CLI fails with error upon non existing transaction ID
  
### Steps to reproduce
- cd lisk-sdk/examples/dpos-mainchain
- /bin/run transaction:get --help 

EXAMPLE
  transaction:get eab06c6a22e88bca7150e0347a7d976acd070cb9284423e6eabecd657acc1263
  
$ ./bin/run transaction:get eab06c6a22e88bca7150e0347a7d976acd070cb9284423e6eabecd657acc1263
Error: Invalid request
    at Object.convertRPCError (~/Projects/lisk-sdk/elements/lisk-api-client/src/utils.ts:19:2)
    at IPCChannel._listenToRPCResponse (~/Projects/lisk-sdk/elements/lisk-api-client/src/ipc_channel.ts:147:39)
$ 

`Note:` Also check for non existing block ID `block:get xxx`

### Which version(s) does this affect? (Environment, OS, etc...)
V6

**Comment by shuse2** [comment]
Closing this issue for no activity
