### ISSUE TITLE
CLI commander should return only error string, rather than throwing the full error stack trace

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7489]
### Description

Currently when one of the validation error fails, CLI commander fails with full error stack trace. 

Example: 
```
$ ./bin/run transaction:create token transfer 100000000 --json --passphrase="peanut hundred pen hawk invite exclude brain chunk gadget wait wrong ready" --key-derivation-path=legacy
Error: Application at data path /Users/khalidlightcurve/.lisk/dpos-mainchain is not running.
    at Object.getApiClient (~/Projects/lisk-sdk/commander/src/utils/transaction.ts:111:9)
    at CreateCommand.run (~/Projects/lisk-sdk/commander/src/bootstrapping/commands/transaction/create.ts:316:25)
    at CreateCommand._run (~/Projects/lisk-sdk/node_modules/@oclif/command/lib/command.js:43:31)
 $ ./bin/run transaction:create token transfer 100000000 --json --passphrase="peanut hundred pen hawk invite exclude brain chunk gadget wait wrong ready" --key-derivation-path=legacy
? Please enter: tokenID:  123
? Please enter: amount:  
? Please enter: recipientAddress:  sdfdsf
? Please enter: data:  dfdsfd
Error: Lisk validator found 2 error[s]:
Property '.tokenID' minLength not satisfied
Property '.recipientAddress' minLength not satisfied
    at LiskValidator.validate (~/Projects/lisk-sdk/elements/lisk-validator/src/lisk_validator.ts:74:10)
    at Object.validateTransaction (~/Projects/lisk-sdk/elements/lisk-transactions/src/validate.ts:36:12)
    at Object.signTransactionWithPrivateKey (~/Projects/lisk-sdk/elements/lisk-transactions/src/sign.ts:109:27)
    at validateAndSignTransaction (~/Projects/lisk-sdk/commander/src/bootstrapping/commands/transaction/create.ts:132:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 $ 
```

### Motivation

It should only return the failed validation as an error string

**Comment by shuse2** [comment]
Closing this issue for no activity
