### ISSUE TITLE
`block:get` hex format example doesn't work

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk-sdk#7527]
### Description

```
$ ./bin/run block:get --help                                                          
Get block information for a given id or height.

USAGE
  $ dpos-mainchain block:get INPUT

ARGUMENTS
  INPUT  Height in number or block id in hex format.

OPTIONS
  -d, --data-path=data-path  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  --pretty                   Prints JSON in pretty format rather than condensed.

EXAMPLES
  block:get e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4
  block:get 2
``` 

Here `block:get 2` works, i.e., 
```
$ ./bin/run block:get 2 --pretty
{
  "header": {
    "version": 2,
    "timestamp": 1663156729,
    "height": 2,
    "previousBlockID": "94d6827e0e015cae90e78afd31df3162d1df87ae1b6764e1b5aa88d2439273d0",
    "stateRoot": "290e2c365611f2876b74a7cfa09ed382f78850ec5153c219c5eebef642b15dbd",
    "assetRoot": "5d47eb9c089f5c31c8530546c62bb20346b055ab2fb275ffc4e17e5cd83caeda",
    "eventRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "transactionRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "validatorsHash": "84f3ed67cec1eb7bd6dc3ec01b0d0323021c1e86a3dc760b9b92041c28da31ac",
    "aggregateCommit": {
      "height": 0,
      "aggregationBits": "",
      "certificateSignature": ""
    },
    "generatorAddress": "lsk5y2q2tn35xrnpdc4oag8sa3ktdacmdcahvwqot",
    "maxHeightPrevoted": 0,
    "maxHeightGenerated": 0,
    "signature": "bc894e003f5f07aa880413f9bec1b71d9d8f94cd6ff22bb291e40c0426b12065a33df37e7d935c7d13855687054dec800efb304af034c705622d27e02c00b609",
    "id": "14970ab47e6279f1ed1f8594964ae535c29f44b9581f4aff0908aea465a1f97e"
  },
  "transactions": [],
  "assets": [
    {
      "module": "random",
      "data": {
        "seedReveal": "3ace37b18185417fa8eb3395c337c4e6"
      }
    }
  ]
}
```
While `block:get e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4 ` throws error, i.e., 
```
$ ./bin/run block:get e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4 --pretty
Error: Specified key 03e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4 does not exist
    at Object.convertRPCError (~/Projects/lisk-sdk/elements/lisk-api-client/src/utils.ts:19:2)
    at IPCChannel._listenToRPCResponse (~/Projects/lisk-sdk/elements/lisk-api-client/src/ipc_channel.ts:147:39)
```

### Motivation

- Both of provided examples should work together, if `number` example is working, then `hex` example should also work.

**Comment by shuse2** [comment]
This example is just an example, every time we create a blockchain, it will have different id. Therefore, this issue is invalid
