### ISSUE TITLE
Issue building the application locally

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-sdk#7532]
### Expected behavior
I should be able to build the application locally.

### Actual behavior
I get the following error:

```
@liskhq/lisk-passphrase: ../../node_modules/@types/socketcluster-client/lib/scclientsocket.d.ts:60:5 - error TS2416: Property 'emit' in type 'SCClientSocket' is not assignable to the same property in base type 'Emitter'.
@liskhq/lisk-passphrase:   Type '{ (event: string, data: any, callback?: ((err: Error, responseData: any) => void) | undefined): void; (event: string, ...args: any[]): boolean; }' is not assignable to type '(event: string, ...args: any[]) => Emitter'.
@liskhq/lisk-passphrase:     Type 'void' is not assignable to type 'Emitter'.
@liskhq/lisk-passphrase: 60     emit(event: string, data: any, callback?: (err: Error, responseData: any) => void): void;
@liskhq/lisk-passphrase:        ~~~~
@liskhq/lisk-passphrase: ../../node_modules/@types/socketcluster-client/lib/scclientsocket.d.ts:80:5 - error TS2416: Property 'on' in type 'SCClientSocket' is not assignable to the same property in base type 'Emitter'.
@liskhq/lisk-passphrase:   Type '{ (event: "connecting", listener: () => void): this; (event: "connect", listener: (status: ConnectStatus, processSubscriptions: () => void) => void): this; (event: "close" | "disconnect" | "connectAbort", listener: (code: number, data: string | object) => void): this; (event: "kickOut", listener: (message: string, c...' is not assignable to type '(event: string, listener: Function) => Emitter'.
@liskhq/lisk-passphrase:     Type 'this' is not assignable to type 'Emitter'.
@liskhq/lisk-passphrase:       Type 'SCClientSocket' is not assignable to type 'Emitter'.
@liskhq/lisk-passphrase:         Types of property 'emit' are incompatible.
@liskhq/lisk-passphrase:           Type '{ (event: string, data: any, callback?: ((err: Error, responseData: any) => void) | undefined): void; (event: string, ...args: any[]): boolean; }' is not assignable to type '(event: string, ...args: any[]) => Emitter'.
@liskhq/lisk-passphrase: 80     on(event: "connecting", listener: () => void): this;
@liskhq/lisk-passphrase:        ~~
.
.
.

@liskhq/lisk-passphrase: ../../node_modules/@types/socketcluster-server/scserversocket.d.ts:55:5 - error TS2416: Property 'emit' in type 'SCServerSocket' is not assignable to the same property in base type 'Emitter'.
@liskhq/lisk-passphrase:   Type '{ (event: string, ...args: any[]): boolean; (event: string, data: any, callback?: EmitCallback | undefined, options?: EmitOptions | undefined): void; }' is not assignable to type '(event: string, ...args: any[]) => Emitter'.
@liskhq/lisk-passphrase: 55     emit(event: string, ...args: any[]): boolean;
@liskhq/lisk-passphrase:        ~~~~
@liskhq/lisk-passphrase: ../../node_modules/@types/socketcluster-server/scserversocket.d.ts:56:5 - error TS2416: Property 'emit' in type 'SCServerSocket' is not assignable to the same property in base type 'Emitter'.
@liskhq/lisk-passphrase:   Type '{ (event: string, ...args: any[]): boolean; (event: string, data: any, callback?: EmitCallback | undefined, options?: EmitOptions | undefined): void; }' is not assignable to type '(event: string, ...args: any[]) => Emitter'.
@liskhq/lisk-passphrase: 56     emit(event: string, data: any, callback?: SCServerSocket.EmitCallback, options?: SCServerSocket.EmitOptions): void;
@liskhq/lisk-passphrase:        ~~~~
@liskhq/lisk-passphrase: Found 28 errors.
```

### Steps to reproduce
- Check out to the v6.0.0-alpha.3 tag
- Set your node version
   - I've tried with Node 16.14.2 and Node 16.15.0 and Node 16.15.1
- Install dependencies 
   - I've installed using yarn and npm
   - i've cleaned yarn and npm caches in advance
   - I've also tried installing dependencies using lisk npm registry.
- Build the application
   - I ran `npm run build` and `yarn build`

### Which version(s) does this affect? (Environment, OS, etc...)
v6.0.0-alpha.3

**Comment by reyraa** [comment]
@shuse2 I can confirm that I don't have this issue in v6.0.0-alpha.3. 

Although now I receive a new error:
```
Error: Cannot find module '@oclif/command'
Require stack:
- /Users/reyraa/Projects/lisk/example/bin/run
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/reyraa/Projects/lisk/example/bin/run:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/reyraa/Projects/lisk/example/bin/run' ]
}
/Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/yeoman-generator/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: /Users/reyraa/Projects/lisk/example/bin/run config:create --output config/default
    at makeError (/Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/yeoman-generator/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/yeoman-generator/node_modules/execa/index.js:188:17)
    at InitGenerator.spawnCommand.spawnCommandSync (/Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/yeoman-generator/lib/actions/spawn-command.js:35:16)
    at InitGenerator.end (/Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/dist/bootstrapping/templates/lisk-template-ts/generators/init_generator.js:58:14)
    at Object.<anonymous> (/Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/yeoman-generator/lib/index.js:1009:25)
    at /Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/yeoman-generator/lib/index.js:1010:11)
    at Immediate.<anonymous> (/Users/reyraa/.nvm/versions/node/v16.15.0/lib/node_modules/lisk-commander/node_modules/grouped-queue/lib/subqueue.js:48:34) {
  shortMessage: 'Command failed with exit code 1: /Users/reyraa/Projects/lisk/example/bin/run config:create --output config/default',
  command: '/Users/reyraa/Projects/lisk/example/bin/run config:create --output config/default',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

This seems to be an issue with the dependencies configuration. I managed to install npm packages from the private registry. 

Now when I try to run without any modules created, I get an error:
```
Starting Lisk example at /Users/reyraa/.lisk/example.
 ›   Error: Network default is not supported, supported networks: .
```
I think we can provide a richer and more accurate error massage. Now I proceed to create a module.

When i want to create a module, I get
```
USAGE
  $ lisk generate:module MODULENAME
```
which is correct, but below I get 
```
EXAMPLE
  generate:module nft 5000
```
Which is wrong. modules don't need an ID.

now proceeding to create a command. Similarly, the example provided by help is outdated. commands don't need an ID.
The command is generated successfully. but when it tries to create unit test files I get this error:

```
Creating command skeleton with command name "register" for module "lns"
Using template "lisk-ts"
Generating asset skeleton.
Registering command...
identical .liskrc.json
   create src/app/modules/lns/commands/register_command.ts
   create test/unit/modules/lns/commands/register_command.spec.ts
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOTDIR: not a directory, stat '/Users/reyraa/Projects/lisk/example/test/unit/modules/lns/commands'] {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'stat',
  path: '/Users/reyraa/Projects/lisk/example/test/unit/modules/lns/commands'
}
```

Although I can ignore this and proceed.
