### ISSUE TITLE
The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-sdk#8610]
### Expected behavior
At any condition, it shouldn't crash the node. It should not crash the node

### Actual behavior
```
2023-06-15T23:18:11.255Z INFO sample engine 3545012 [id=2130b72e7655c90c5c3dc8b78730a2f4198daef3f1d4f13b1c878f9b39b66049 height=251410 generator=lsk3oe7hmf5k5e4f58zhmbouzx3t4v98sgsfuhwnw numberOfTransactions=1 numberOfAssets=1 numberOfEvents=9] Block executed
2023-06-15T23:18:11.256Z INFO sample engine 3545012 [status=success event=chain_newBlock] IPCServer published event
2023-06-15T23:18:11.257Z INFO sample engine 3545012 [status=success event=network_newBlock] IPCServer published event
2023-06-15T23:18:11.266Z INFO sample engine 3545012 [status=success event=chain_newBlock] WSServer published event
2023-06-15T23:18:11.270Z INFO sample engine 3545012 [status=success event=network_newBlock] WSServer published event
2023-06-15T23:18:11.489Z FATAL sample application 3545012 [err=The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined] System error: unhandledRejection
```

### Steps to reproduce
Unknown

### Which version(s) does this affect? (Environment, OS, etc...)
beta.1-

**Comment by przemerr** [comment]
@shuse2 was playing around today with the betanode, applied a snapshot and tried to sync, got the same error, but have some trace logs, not sure if this is related, or just a coincidence:

```
2023-06-19T08:04:30.570Z INFO vps engine 3169202 Engine cleanup completed
2023-06-19T08:04:30.571Z ERROR vps engine 3169202 [peerId=137.220.55.37:7667 err=Peer not found: 137.220.55.37:7667 trace=Error: Peer not found: 137.220.55.37:7667
    at PeerPool.applyPenalty (/home/lisk-beta/.nvm/versions/node/v18.16.0/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-p2p/dist-node/peer_pool.js:323:19)
    at P2P.applyPenalty (/home/lisk-beta/.nvm/versions/node/v18.16.0/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-p2p/dist-node/p2p.js:351:24)
    at Network.applyPenaltyOnPeer (/home/lisk-beta/.nvm/versions/node/v18.16.0/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/engine/network/network.js:303:26)
    at Consensus._sync (/home/lisk-beta/.nvm/versions/node/v18.16.0/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/consensus.js:589:31)
    at async /home/lisk-beta/.nvm/versions/node/v18.16.0/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/consensus.js:310:17
    at async Mutex.runExclusive (/home/lisk-beta/.nvm/versions/node/v18.16.0/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-utils/dist-node/job_handlers/mutex.js:23:20)
    at async Consensus._execute (/home/lisk-beta/.nvm/versions/node/v18.16.0/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/consensus.js:252:9)
    at async Consensus.onBlockReceive (/home/lisk-beta/.nvm/versions/node/v18.16.0/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/engine/consensus/consensus.js:192:13)] Fail to handle received block
2023-06-19T08:04:30.571Z INFO vps application 3169202 Stopping Controller
2023-06-19T08:04:30.572Z DEBUG vps application 3169202 Reason: The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined
2023-06-19T08:04:30.572Z DEBUG vps application 3169202 Plugins cleanup started
2023-06-19T08:04:30.572Z DEBUG vps application 3169202 Plugins cleanup completed
2023-06-19T08:04:30.573Z DEBUG vps application 3169202 Bus cleanup started
2023-06-19T08:04:30.574Z DEBUG vps application 3169202 Bus cleanup completed
2023-06-19T08:04:30.574Z INFO vps application 3169202 Controller cleanup completed
2023-06-19T08:04:30.583Z INFO vps application 3169202 [errorCode=1 message=The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined] Application shutdown completed
```

**Comment by shuse2** [comment]
Logging the stack, i found
``
unhandledRejection TypeError [ERR_INVALID_ARG_TYPE]: The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Uint8Array.equals (node:buffer:876:11)
    at TransactionPool._reorganize (//lisk-core/node_modules/@liskhq/lisk-transaction-pool/dist-node/transaction_pool.js:256:54)
    at async Timeout._onTimeout (//lisk-core/node_modules/@liskhq/lisk-transaction-pool/dist-node/job.js:26:17)
2023-06-20T08:03:51.866Z FATAL vpn application 95372 [stack=TypeError [ERR_INVALID_ARG_TYPE]: The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Uint8Array.equals (node:buffer:876:11)
    at TransactionPool._reorganize (//lisk-core/node_modules/@liskhq/lisk-transaction-pool/dist-node/transaction_pool.js:256:54)
    at async Timeout._onTimeout (//lisk-core/node_modules/@liskhq/lisk-transaction-pool/dist-node/job.js:26:17) err=The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined] System error: unhandledRejection
2023-06-20T08:03:51.866Z INFO vpn application 95372 [errorCode=1 message=The "otherBuffer" argument must be an instance of Buffer or Uint8Array. Received undefined] Application shutdown started
```
