### ISSUE TITLE
Custom CCM fails to be sent on sidechain

### ISSUE THREAD

**Issue by ishantiw** [LiskHQ/lisk-sdk#9087]
### Expected behavior

Custom CCM from a sidechain should be accepted by the supporting sidechain in the ecosystem.

### Actual behavior

Custom CCM fails on execution at `verifyPartnerChainOutboxRoot` with Error `Error: Invalid inclusion proof for inbox update.`

```
 at SidechainInteroperabilityInternalMethod.verifyPartnerChainOutboxRoot (/Users/ishan/repos/sdk/sdk2/lisk-sdk/framework/dist-node/modules/interoperability/base_interoperability_internal_methods.js:439:19)
18|pos-sidechain-1  |     at async SubmitSidechainCrossChainUpdateCommand.executeCommon (/Users/ishan/repos/sdk/sdk2/lisk-sdk/framework/dist-node/modules/interoperability/base_cross_chain_update_command.js:75:17)
18|pos-sidechain-1  |     at async SubmitSidechainCrossChainUpdateCommand.execute (/Users/ishan/repos/sdk/sdk2/lisk-sdk/framework/dist-node/modules/interoperability/sidechain/commands/submit_sidechain_cross_chain_update.js:18:35)
18|pos-sidechain-1  |     at async StateMachine.executeTransaction (/Users/ishan/repos/sdk/sdk2/lisk-sdk/framework/dist-node/state_machine/state_machine.js:132:13)
18|pos-sidechain-1  |     at async ABIHandler.executeTransaction (/Users/ishan/repos/sdk/sdk2/lisk-sdk/framework/dist-node/abi_handler/abi_handler.js:287:24)
18|pos-sidechain-1  |     at async HighFeeGenerationStrategy.getTransactionsForBlock (/Users/ishan/repos/sdk/sdk2/lisk-sdk/framework/dist-node/engine/generator/strategies.js:45:75)
18|pos-sidechain-1  |     at async Generator._generateBlock (/Users/ishan/repos/sdk/sdk2/lisk-sdk/framework/dist-node/engine/generator/generator.js:365:69)
18|pos-sidechain-1  |     at async Generator._generateLoop (/Users/ishan/repos/sdk/sdk2/lisk-sdk/framework/dist-node/engine/generator/generator.js:299:32)
18|pos-sidechain-1  |     at async Timeout._onTimeout (/Users/ishan/repos/sdk/sdk2/lisk-sdk/elements/lisk-utils/dist-node/job_handlers/scheduler.js:26:17)
```

### Steps to reproduce

- With 2 sidechains, try to send a custom CCM from one sidechain to another and observe error

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-rc.3`

**Comment by ishantiw** [comment]
Resolved in #9099
